export default [
	{ href: "./html/yohoho.io/index.html", imgSrc: "yohoho.io.jfif", name: "yohoho.io" },
	{ href: "./html/smash karts/index.html", imgSrc: "smash karts.avif", name: "Smash Karts" },
	{ href: "./html/pathfinder/index.html", imgSrc: "Screenshot 2024-07-09 144933.png", name: "Pathfinder" },
	{ href: "./html/ovo/index.html", imgSrc: "ovo.png", name: "Ovo" },
	{ href: "./html/hasty shaman/index.html", imgSrc: "hasty shaman.png", name: "Hasty Shaman" },
	{ href: "./html/one trick mage/index.html", imgSrc: "one trick mage.png", name: "One Trick Mage" },
	{ href: "./swf/arcuz/base.html", imgSrc: "arcuz.jpg", name: "Arcuz" },
	{ href: "./swf/age of war/base.html", imgSrc: "age of war.jpg", name: "Age of war" },
	{ href: "./html/winter gifts/index.html", imgSrc: "winter gifts.jpg", name: "Winter Gifts" },
	{ href: "./html/tough growth/index.html", imgSrc: "tough growth.jpg", name: "Tough Growth" },
	{ href: "./html/the dark one/index.html", imgSrc: "the dark one.jpg", name: "The Dark One" },
	{ href: "./html/tactical weapon pack/index.html", imgSrc: "tactical weapon pack.png", name: "Tactical Weapon Pack" },
	{ href: "./html/soul mirror/index.html", imgSrc: "soul mirror.jpg", name: "Soul Mirror" },
	{ href: "./html/push/index.html", imgSrc: "push.jpg", name: "Push" },
	{ href: "./html/progress knight/index.html", imgSrc: "progress knight.png", name: "Progress Knight" },
	{ href: "./html/pe norie/index.html", imgSrc: "pe norie.jpg", name: "Pe Norie" },
	{ href: "./html/orange/index.html", imgSrc: "orange.png", name: "Orange" },
	{ href: "./html/mini sticky/index.html", imgSrc: "mini sticky.avif", name: "Mini Sticky" },
	{ href: "./html/mini jumps/index.html", imgSrc: "mini jumps.png", name: "Mini Jumps" },
	{ href: "./html/life in the static/index.html", imgSrc: "life in the static.jpg", name: "Life in the Static" },
	{ href: "./html/laqueus escape chapter 1/index.html", imgSrc: "laqueus escape chapter 1.avif", name: "Laqueus Escape Chapter 1" },
	{ href: "./html/just passing/index.html", imgSrc: "just passing.png", name: "Just Passing" },
	{ href: "./html/hexa knot/index.html", imgSrc: "hexa knot.png", name: "Hexa Knot" },
	{ href: "./html/goodbye doggy/index.html", imgSrc: "goodbye doggy.jpg", name: "Goodbye Doggy" },
	{ href: "./html/generic fishing game/index.html", imgSrc: "generic fishing game.png", name: "Generic Fishing Game" },
	{ href: "./html/dubstep raven/index.html", imgSrc: "dubstep raven.png", name: "Dubstep Raven" },
	{ href: "./html/doodle alive/index.html", imgSrc: "doodle alive.jpg", name: "Doodle Alive" },
	{ href: "./html/detective bass fish/index.html", imgSrc: "detective bass fish.webp", name: "Detective Bass Fish" },
	{ href: "./html/cursed travels below/index.html", imgSrc: "cursed travels below.png", name: "Cursed Travels Below" },
	{ href: "./html/clickventure castaway/index.html", imgSrc: "clickventure castaway.jpg", name: "Clickventure Castaway" },
	{ href: "./html/choppy orc/index.html", imgSrc: "choppy orc.jpg", name: "Choppy Orc" },
	{ href: "./html/cataractae/index.html", imgSrc: "cataractae.jpg", name: "Cataractae" },
	{ href: "./html/cat house/index.html", imgSrc: "cat house.avif", name: "Cat House" },
	{ href: "./html/cardinal chains/index.html", imgSrc: "cardinal chains.png", name: "Cardinal Chains" },
	{ href: "./html/bunnies carrot/index.html", imgSrc: "bunnies carrot.jpg", name: "Bunnies Carrot" },
	{ href: "./html/aspiring artist/index.html", imgSrc: "aspiring artist.webp", name: "Aspiring Artist" },
	{ href: "./html/arcade wizard/index.html", imgSrc: "arcade wizard.png", name: "Arcade Wizard" },
	{ href: "./html/ant art tycoon/index.html", imgSrc: "ant art tycoon.png", name: "Ant Art Tycoon" },
	{ href: "./swf/swords and souls/base.html", imgSrc: "swords and souls.avif", name: "Swords and Souls" },
	{ href: "./swf/sonny2/base.html", imgSrc: "sonny2.jpg", name: "Sonny2" },
	{ href: "./swf/sonny/base.html", imgSrc: "sonny.png", name: "Sonny" },
	{ href: "./swf/kingdom rush frontie/base.html", imgSrc: "kingdom rush frontie.jpg", name: "Kingdom Rush Frontie" },
	{ href: "./swf/kingdom rush/base.html", imgSrc: "kingdom rush.jpg", name: "Kingdom Rush" },
	{ href: "./html/worlds within worlds/index.html", imgSrc: "worlds within worlds.png", name: "Worlds Within Worlds" },
	{ href: "./html/unloop/index.html", imgSrc: "unloop.jpg", name: "Unloop" },
	{ href: "./html/tower of the scorche/index.html", imgSrc: "tower of the scorche.png", name: "Tower of the Scorche" },
	{ href: "./html/there is no game/index.html", imgSrc: "there is no game.jpg", name: "There is No Game" },
	{ href: "./html/scalak/index.html", imgSrc: "scalak.jpg", name: "Scalak" },
	{ href: "./html/sabotage/index.html", imgSrc: "sabotage.webp", name: "Sabotage" },
	{ href: "./html/roots/index.html", imgSrc: "roots.jpg", name: "Roots" },
	{ href: "./html/rogue fable/index.html", imgSrc: "rogue fable.jpg", name: "Rogue Fable" },
	{ href: "./html/pixoji/index.html", imgSrc: "pixoji.png", name: "Pixoji" },
	{ href: "./html/pink/index.html", imgSrc: "pink.png", name: "Pink" },
	{ href: "./html/knight errant/index.html", imgSrc: "knight errant.png", name: "Knight Errant" },
	{ href: "./html/hexologic/index.html", imgSrc: "hexlogic.jpg", name: "Hexologic" },
	{ href: "./html/gragyriss/index.html", imgSrc: "gragyriss.avif", name: "Gragyriss" },
	{ href: "./html/gem twins/index.html", imgSrc: "gem twins.png", name: "Gem Twins" },
	{ href: "./html/dinogen arena/index.html", imgSrc: "dinogen arena.webp", name: "Ginogen Arena" },
	{ href: "./html/cursed travels flame/index.html", imgSrc: "cursed travels flame.png", name: "Cursed Travels Flame" },
	{ href: "./html/clickventure/index.html", imgSrc: "clickbenture.jpg", name: "Clickventure" },
	{ href: "./html/blue/index.html", imgSrc: "blue.png", name: "Blue" },
	{ href: "./html/beam/index.html", imgSrc: "beam.png", name: "Beam" },
	{ href: "./html/a grim love tale/index.html", imgSrc: "a grim love tale.jpg", name: "A Grim Love Tale" },
	{ href: "./html/a grim chase/index.html", imgSrc: "a grim chase.jpg", name: "A Grim Chase" },
	{ href: "./html/babel tower/index.html", imgSrc: "Babel tower.avif", name: "Babel Tower" },
	{ href: "./html/tavern master/index.html", imgSrc: "tavern master.png", name: "Tavern Master" },
	{ href: "./html/green/index.html", imgSrc: "green.png", name: "Green" },
	{ href: "./swf/stealing the diamond/base.html", imgSrc: "stealing the diamond.jpg", name: "Stealing the Diamond" },
	{ href: "./swf/infiltrating the airship/base.html", imgSrc: "infiltrating the airship.jpg", name: "Infiltrating the Airship" },
	{ href: "./swf/fleeing the complex/base.html", imgSrc: "fleeing the complex.jpg", name: "Fleeing the Complex" },
	{ href: "./swf/escaping the prison/base.html", imgSrc: "escaping the pirson.jpg", name: "Escaping the Prison" },
	{ href: "./swf/breaking the bank/base.html", imgSrc: "breaking the bank.jpg", name: "Breaking the Bank" },
	{ href: "./html/tanuki sunset/index.html", imgSrc: "tanuki sunset.jpg", name: "Tanuki Sunset" },
	{ href: "./html/Soccer Random/index.html", imgSrc: "Soccor Random.avif", name: "Soccer Random" },
	{ href: "./html/ricochet arrow/index.html", imgSrc: "ricochet arrow.jpg", name: "Ricochet Arrow" },
	{ href: "./html/Pixel Battles/index.html", imgSrc: "Pixel Battles.jpg", name: "Pixel Battles" },
	{ href: "./html/oil race/index.html", imgSrc: "oil race.avif", name: "Oil Race" },
	{ href: "./html/Mountain Biking/index.html", imgSrc: "Mountain Biking.jpg", name: "Mountain Biking" },
	{ href: "./html/monkey mart/index.html", imgSrc: "monkey mart.png", name: "Monkey Mart" },
	{ href: "./html/maptroid/index.html", imgSrc: "maptroid.jpg", name: "Maptroid" },
	{ href: "./html/hover racer drive/index.html", imgSrc: "hover racer drive.png", name: "Hover Racer Drive" },
	{ href: "./html/hole.io/index.html", imgSrc: "hole.io.jpg", name: "Hole.io" },
	{ href: "./html/erase box/index.html", imgSrc: "erase box.jpg", name: "Erase Box" },
	{ href: "./html/Basket Random/index.html", imgSrc: "Basket Random.jpg", name: "Basket Random" },
	{ href: "./swf/gun mayhem 2/base.html", imgSrc: "gun mayhem 2.jpg", name: "Gun Mayhem 2" },
	{ href: "./html/shortcut race/index.html", imgSrc: "shortcut race.jpg", name: "Shortcut Race" },
	{ href: "./swf/alienthief/base.html", imgSrc: "alienthief.jpg", name: "Alien Theif" },
	{ href: "./swf/checkpoint/base.html", imgSrc: "checkpoint.jpg", name: "Checkpoint" },
	{ href: "./swf/chimneytrouble/base.html", imgSrc: "chimneytrouble.jpg", name: "Chimney Trouble" },
	{ href: "./swf/diasterwillstrike/base.html", imgSrc: "disasterwillstrike.jpg", name: "Disaster Will Strike" },
	{ href: "./swf/drakeandthewizards/base.html", imgSrc: "drakeandthewizards.jpg", name: "Drake and the Wizards" },
	{ href: "./swf/electricman2/base.html", imgSrc: "electricman2.jpg", name: "Electric Man 2" },
	{ href: "./swf/freegear/base.html", imgSrc: "freegear.jpg", name: "Freegear" },
	{ href: "./swf/gooballs/base.html", imgSrc: "gooballs.jpg", name: "Gooballs" },
	{ href: "./swf/hoshisaga1/base.html", imgSrc: "hoshisaga1.png", name: "Hoshi Saga 1" },
	{ href: "./swf/hoshisaga2/base.html", imgSrc: "hoshisaga2.jpg", name: "Hoshi Saga 2" },
	{ href: "./swf/hoshisaga3/base.html", imgSrc: "hoshisaga3.jpg", name: "Hoshi Saga 3" },
	{ href: "./swf/iqball/base.html", imgSrc: "iqball.jpg", name: "IQ Ball" },
	{ href: "./swf/iwannawin/base.html", imgSrc: "iwannawin.jpg", name: "I Wanna Win" },
	{ href: "./swf/jellygo/base.html", imgSrc: "jellygo.jpg", name: "Jelly Go!" },
	{ href: "./swf/littlewheel/base.html", imgSrc: "littlewheel.jpg", name: "Little Wheel" },
	{ href: "./swf/miniputt3/base.html", imgSrc: "miniputt3.jpg", name: "Mini Putt 3" },
	{ href: "./swf/minitrain/base.html", imgSrc: "minitrain.jpg", name: "Mini Train" },
	{ href: "./swf/papabakeria/base.html", imgSrc: "papasbakeria.jpg", name: "Papas Bakeria" },
	{ href: "./swf/papaburgeria/base.html", imgSrc: "papasburgeria.jpg", name: "Papas Burgeria" },
	{ href: "./swf/papacheeseria/base.html", imgSrc: "papascheeseria.jpg", name: "Papas Cheeseria" },
	{ href: "./swf/papacupcakeria/base.html", imgSrc: "papascupcakeria.jpg", name: "Papas Cupcakeria" },
	{ href: "./swf/papadonuteria/base.html", imgSrc: "papadonuteria.jpg", name: "Papas Donuteria" },
	{ href: "./swf/papafreezeria/base.html", imgSrc: "papasfreezeria.jpg", name: "Papas Freezeria" },
	{ href: "./swf/papahotdoggeria/base.html", imgSrc: "papashotdoggeria.jpg", name: "Papas Hotdoggeria" },
	{ href: "./swf/papapancakeria/base.html", imgSrc: "papaspancakeria.jpg", name: "Papas Pancakeria" },
	{ href: "./swf/papapasteria/base.html", imgSrc: "papaspasteria.jpg", name: "Papas Pasteria" },
	{ href: "./swf/papapizzeria/base.html", imgSrc: "papaspizzeria.jpg", name: "Papas Pizzeria" },
	{ href: "./swf/papascooperia/base.html", imgSrc: "papasscooperia.jpg", name: "Papas Scooperia" },
	{ href: "./swf/papasushiria/base.html", imgSrc: "papassushiria.jpg", name: "Papas Sushiria" },
	{ href: "./swf/papataco/base.html", imgSrc: "papataco.jpg", name: "Papas Taco Mia" },
	{ href: "./swf/papawingeria/base.html", imgSrc: "papawingeria.jpg", name: "Papas Wingeria" },
	{ href: "./swf/portal/base.html", imgSrc: "portal.jpg", name: "Portal" },
	{ href: "./swf/pvz2/base.html", imgSrc: "pvz2.jpg", name: "Plants Vs. Zombies 2" },
	{ href: "./swf/raftwars/base.html", imgSrc: "raftwars.jpg", name: "Raft Wars" },
	{ href: "./swf/scrapmeatalheros/base.html", imgSrc: "scrapmeatalheros.jpg", name: "Scrap Meatal Heros" },
	{ href: "./swf/shapeshifter/base.html", imgSrc: "shapeshifter.png", name: "Shape Shifter" },
	{ href: "./swf/squarehero/base.html", imgSrc: "squarehero.jpg", name: "Square Hero" },
	{ href: "./swf/tarzanball/base.html", imgSrc: "tarzanball.jpg", name: "Tarzan Ball" },
	{ href: "./swf/tastyplanetdinotime/base.html", imgSrc: "tastyplanetdinotime.jpg", name: "Tasty Planet Dinotime" },
	{ href: "./swf/truckloader/base.html", imgSrc: "truckloader.jpg", name: "Truck Loader" },
	{ href: "./swf/workingstiffs/base.html", imgSrc: "workingstiffs.jpg", name: "Working Stiffs" },
	{ href: "./html/eaglecraft/game/Offline_Download_Version.html", imgSrc: "minecraft.jpeg", name: "Minecraft (1.5.2 Eaglercraft)" },
	{ href: "./html/sm64/index.html", imgSrc: "sm64.jpg", name: "Super Mario 64" },
	{ href: "./html/rocket league/index.html", imgSrc: "rocketleague.jpg", name: "Rocket League" },
	{ href: "./html/google-snake/index.html", imgSrc: "googlesnake.jpg", name: "Google Snake" },
	{ href: "./html/stickman-hook/index.html", imgSrc: "stickmanhook.jpg", name: "Stickman Hook" },
	{ href: "./html/slope2/index.html", imgSrc: "slope2.jpg", name: "Slope 2" },
	{ href: "./html/slope/index.html", imgSrc: "slope.webp", name: "Slope" },
	{ href: "./html/bitlife/index.html", imgSrc: "bitlife.jpg", name: "Bitlife" },
	{ href: "./html/drift-boss/index.html", imgSrc: "drift-boss.png", name: "Drift Boss" },
	{ href: "./html/snow-rider-3d/index.html", imgSrc: "snow-rider-3d-unblocked.png", name: "Snow Rider 3D" },
	{ href: "./html/planetlife/index.html", imgSrc: "planetlife.jpg", name: "Planet Life" },
	{ href: "./swf/findingsanta/base.html", imgSrc: "santa.png", name: "Finding Santa" },
	{ href: "./swf/hauntthehouse/base.html", imgSrc: "hauntthehouse.jpg", name: "Haunt the House" },
	{ href: "./html/houseofhazards/index.html", imgSrc: "houseofhazards.jpg", name: "House of Hazards" },
	{ href: "./html/couch2048/index.html", imgSrc: "couch.jpg", name: "Couch 2048" },
	{ href: "./html/tabs/index.html", imgSrc: "tabs.jpeg", name: "Tabs" },
	{ href: "./html/catpitolists/advcap.html", imgSrc: "capitolist.jpeg", name: "AdVenture Capitolists" },
	{ href: "./swf/ducklife1/base.html", imgSrc: "ducklife.webp", name: "Duck Life" },
	{ href: "./swf/ducklife2/base.html", imgSrc: "ducklife2.webp", name: "Duck Life 2" },
	{ href: "./swf/ducklife3/base.html", imgSrc: "ducklife3.webp", name: "Duck Life 3" },
	{ href: "./swf/factoryballs1/base.html", imgSrc: "factoryballs1.jpeg", name: "Factory Balls 1" },
	{ href: "./swf/factoryballs2/base.html", imgSrc: "factoryballs2.jpeg", name: "Factory Balls 2" },
	{ href: "./swf/factoryballs3/base.html", imgSrc: "factoryballs3.jpeg", name: "Factory Balls 3" },
	{ href: "./swf/factoryballs4/base.html", imgSrc: "factoryballs4.jpeg", name: "Factory Balls 4" },
	{ href: "./swf/run/base.html", imgSrc: "run.jpeg", name: "Run 1" },
	{ href: "./swf/run2/base.html", imgSrc: "run2.jpeg", name: "Run 2" },
	{ href: "./html/bitts/index.html", imgSrc: "bitts.png", name: "Big Ice Tower Tiny Square" },
	{ href: "./swf/fancy1/base.html", imgSrc: "fancy1.jpg", name: "Fancy Pants 1" },
	{ href: "./swf/fancy3/base.html", imgSrc: "fancy3.jpg", name: "Fancy Pants 3" },
	{ href: "./swf/penguin/base.html", imgSrc: "penguin.jpeg", name: "Penguin Dinner" },
	{ href: "./swf/bombit/base.html", imgSrc: "bombit.jpeg", name: "Bombit 1" },
	{ href: "./swf/bombit2/base.html", imgSrc: "bombit2.jpeg", name: "Bombit 2" },
	{ href: "./swf/bombit3/base.html", imgSrc: "bombit3.jpg", name: "Bombit 3" },
	{ href: "./swf/comicbook/base.html", imgSrc: "comicbook.jpeg", name: "Comic Book Cody" },
	{ href: "./swf/hotdogbush/base.html", imgSrc: "hotdogbush.jpeg", name: "Hot Dog Bush" },
	{ href: "./swf/louie1/base.html", imgSrc: "louie1.jpeg", name: "Papa Louies 1" },
	{ href: "./swf/minhero/base.html", imgSrc: "minhero.jpeg", name: "Min Hero Tower of Sages" },
	{ href: "./swf/pandas1/base.html", imgSrc: "pandas1.jpeg", name: "3 Pandas 1" },
	{ href: "./swf/shapeswitch/base.html", imgSrc: "shapeswitcher.jpeg", name: "Shape Switcher" },
	{ href: "./swf/strikeforcekitty/base.html", imgSrc: "strikeforcekitty.jpeg", name: "Strike Force Kitty 1" },
	{ href: "./swf/strikeforcekitty2/base.html", imgSrc: "strikeforcekitty2.jpeg", name: "Strike Force Kitty 2" },
	{ href: "./swf/strikeforcekitty3/base.html", imgSrc: "strikeforcekitty3.jpeg", name: "Strike Force Kitty 3" },
	{ href: "./swf/sugar/base.html", imgSrc: "sugar.jpeg", name: "Sugar, Sugar" },
	{ href: "./html/finalearth2/index.html", imgSrc: "finalearth2.png", name: "Final Earth 2" },
	{ href: "./html/drive-mad/index.html", imgSrc: "drivemad.jpg", name: "Drive Mad" },
	{ href: "./html/among-us/index.html", imgSrc: "amongus.png", name: "Among Us" },
	{ href: "./html/bob-the-robber-2/index.html", imgSrc: "bob.jpeg", name: "Bob the Robber 2" },
	{ href: "./html/tiny-fishing/index.html", imgSrc: "fishing.jpeg", name: "Tiny Fishing" },
	{ href: "./html/2048-master/2048-master/index.html", imgSrc: "2048.png", name: "2048" },
	{ href: "./html/adarkroom/index.html", imgSrc: "adarkroom.png", name: "A Dark Room" },
	{ href: "./html/algaes-escapade/index.html", imgSrc: "apple-touch-icon-114x114.png", name: "Algaes Escapade" },
	{ href: "./html/Alien Invasion/Alien Invasion/index.html", imgSrc: "alien.png", name: "Alien Invasion" },
	{ href: "./html/Appel/game/Appel.html", imgSrc: "appel.png", name: "Appel" },
	{ href: "./html/asciispace/index.html", imgSrc: "asciispace.png", name: "Asciispace" },
	{ href: "./html/asteroids/index.html", imgSrc: "asteroids.png", name: "Asteroids" },
	{ href: "./html/astray/index.html", imgSrc: "astray.png", name: "Astray" },
	{ href: "./html/ball platformer/game/ball platformer.html", imgSrc: "ball platformer.png", name: "Ball Platformer" },
	{ href: "./html/blackholesquare/index.html", imgSrc: "BlackHoleSquare.png", name: "Blackholesquare" },
	{ href: "./html/bloxorz/game/index.html", imgSrc: "bloxorz.png", name: "Bloxorz" },
	{ href: "./html/bounceback/index.html", imgSrc: "bounceback.png", name: "Bounceback" },
	{ href: "./html/breaklock/index.html", imgSrc: "breaklock.png", name: "Breaklock" },
	{ href: "./html/breakout/index.html", imgSrc: "breakout.png", name: "Breakout" },
	{ href: "./html/Bubble Scratch/game/Bubble Scratch.html", imgSrc: "bubble scratch.png", name: "Bubble Scratch" },
	{ href: "./html/c4/game/index.html", imgSrc: "c4.png", name: "Connect 4" },
	{ href: "./html/captaincallisto/index.html", imgSrc: "capain.png", name: "Captain Callisto" },
	{ href: "./html/chess/index.html", imgSrc: "chess.png", name: "Chess" },
	{ href: "./html/chroma/index.html", imgSrc: "chroma.png", name: "Chroma" },
	{ href: "./html/cookieclicker/index.html", imgSrc: "cookie.png", name: "Cookie Clicker" },
	{ href: "./html/Crystal Seeker.html", imgSrc: "crystal.png", name: "Crystal Seeker" },
	{ href: "./html/Cube Miner/game/Cube Miner.html", imgSrc: "cube.png", name: "Cube Miner" },
	{ href: "./html/cubefield/index.html", imgSrc: "cubefeild.png", name: "Cubefield" },
	{ href: "./html/digger-main/digger-main/index.html", imgSrc: "diggermain.png", name: "Digger Main" },
	{ href: "./html/dinosaur/index.html", imgSrc: "dino.png", name: "Dinosaur" },
	{ href: "./html/edgenotfound/index.html", imgSrc: "edge.png", name: "Edge Not Found" },
	{ href: "./html/evilglitch/index.html", imgSrc: "EvilGlitch.png", name: "Evil Glich" },
	{ href: "./html/flappy-2048/index.html", imgSrc: "flappy2048.png", name: "Flappy 2048" },
	{ href: "./html/flappybird/index.html", imgSrc: "FlappyBird.png", name: "Flappy Bird" },
	{ href: "./html/Fortnite Z/game/Fortnite Z.html", imgSrc: "fornitez.png", name: "Fortnite Z" },
	{ href: "./html/fruitninja/index.html", imgSrc: "fruit.png", name: "Fruit Ninja" },
	{ href: "./html/Geometry Dash Meltdown/game/Geometry Dash Meltdown.html", imgSrc: "dashmeltdown.png", name: "Geometry Dash Meltdown" },
	{ href: "./html/Geometry Dash Subzero/game/Geometry Dash Subzero.html", imgSrc: "dashsubzero.png", name: "Geometry Dash Subzero" },
	{ href: "./html/Geometry Dash v1/game/Geometry Dash v1.html", imgSrc: "dash.png", name: "Geometry Dash" },
	{ href: "./html/Geometry Dash World Toxic factory/game/Geometry Dash World Toxic factory.html", imgSrc: "dashtoxic.png", name: "Geometry Dash World Toxic" },
	{ href: "./html/Getting Over It v1/game/Getting Over It v1.html", imgSrc: "over.png", name: "Getting Over It" },
	{ href: "./html/hearse mster/-=HORSE MASTER=- The Game of Horse Mastery.html", imgSrc: "horse.png", name: "Horse Master" },
	{ href: "./html/hextris/index.html", imgSrc: "hex.png", name: "Hextris" },
	{ href: "./html/html5-farming-demo-master/html5-farming-demo-master/farming.html", imgSrc: "farm.png", name: "Farming" },
	{ href: "./html/konnekt/index.html", imgSrc: "cone.png", name: "Konnekt" },
	{ href: "./html/Mario/game/Mario.html", imgSrc: "Mario.png", name: "Mario" },
	{ href: "./html/minekhan/index.html", imgSrc: "khan.png", name: "MineKahn" },
	{ href: "./html/Paper Minecraft/game/Paper Minecraft.html", imgSrc: "papermc.png", name: "Paper Minecraft" },
	{ href: "./html/packabunchas/index.html", imgSrc: "pack.png", name: "Packabunchas" },
	{ href: "./html/just one boss/index.html", imgSrc: "oneboss.png", name: "Just One Boss" },
	{ href: "./html/pushback/index.html", imgSrc: "back.png", name: "Push Back" },
	{ href: "./html/racer/index.html", imgSrc: "racer.jpeg", name: "Racer" },
	{ href: "./html/radius raid/radius raid/index.html", imgSrc: "radius.png", name: "Radius Raid" },
	{ href: "./html/pico-8/PICO-8 Cartridge.html", imgSrc: "pcraft.png", name: "P-Craft" },
	{ href: "./html/retrohaunt/index.html", imgSrc: "retro.jpeg", name: "Retrohaunt" },
	{ href: "./html/roadblocks/index.html", imgSrc: "roadblocks.jpeg", name: "Roadblocks" },
	{ href: "./html/shuttledeck/index.html", imgSrc: "shuttle.png", name: "Shuttledeck" },
	{ href: "./html/sleeping beauty/sleeping beauty/index.html", imgSrc: "sleeping.png", name: "Sleeping Beauty" },
	{ href: "./html/spacecompany/index.html", imgSrc: "images.png", name: "Space Company" },
	{ href: "./html/spacegarden/index.html", imgSrc: "garden.jpeg", name: "Space Garden" },
	{ href: "./html/spacehuggers/index.html", imgSrc: "huggers.jpeg", name: "Space Huggers" },
	{ href: "./html/stack/stack/index.html", imgSrc: "stack.jpeg", name: "Stack" },
	{ href: "./html/tetris advanced/index.html", imgSrc: "tetris.jpeg", name: "Tetris" },
	{ href: "./html/trimps/index.html", imgSrc: "trimps.png", name: "Trimps" },
	{ href: "./html/xx142-b2exe/index.html", imgSrc: "xx.png", name: "xx142-b2exe" },
	{ href: "./html/Sand and Water v3.html", imgSrc: "sand.png", name: "Sand and Water" },
	{ href: "./html/Scratch Brawl 2.html", imgSrc: "scratchb.jpg", name: "Scratch Brawl 2" },
	{ href: "./html/slither.io v1.html", imgSrc: "slither.png", name: "Slither.io" },
	{ href: "./html/Terrain Generator.html", imgSrc: "terrain.png", name: "Terrain Generator" },
	{ href: "./html/Terraria.html", imgSrc: "terraria.jpg", name: "Terraria" },
	{ href: "./html/The Ninja.html", imgSrc: "n1.webp", name: "The Ninja" },
	{ href: "./html/The Ninja 2.html", imgSrc: "n2.png", name: "The Ninja 2" },
	{ href: "./html/The Ninja 3.html", imgSrc: "n3.webp", name: "The Ninja 3" },
	{ href: "./html/The Ninja 4.html", imgSrc: "n4.jpg", name: "The Ninja 4" },
	{ href: "./html/The Ninja 5.html", imgSrc: "n5.webp", name: "The Ninja 5" },
	{ href: "./html/The Ninja 5 Hacked!.html", imgSrc: "n5h.png", name: "The Ninja 5 Hacked" },
	{ href: "./html/100uc.html", imgSrc: "100uc.png", name: "$100 Unicorn" },
	{ href: "./html/theexocutor", imgSrc: "executor.png", name: "The Executor" },
	{ href: "./html/1v1/index.html", imgSrc: "1v1.webp", name: "1v1.lol" },
	{ href: "./html/1v1space/index.html", imgSrc: "1v1space.webp", name: "1v1 Space" },
	{ href: "./html/10-minutes-till-dawn/index.html", imgSrc: "10m.webp", name: "10 Minutes Till Dawn" },
	{ href: "./html/100-player-pong/index.html", imgSrc: "100pong.webp", name: "100 Pong" },
	{ href: "./html/9007199254740992/index.html", imgSrc: "900.webp", name: "9007199254740992" },
	{ href: "./html/achievementunlocked/index.html", imgSrc: "ache.webp", name: "Achievementunlocked" },
	{ href: "./html/ages-of-conflict/index.html", imgSrc: "ages-of-conflict.webp", name: "Ages of Conflict" },
	{ href: "./html/alienhominid/index.html", imgSrc: "alienhominid.webp", name: "Alien Hominid" },
	{ href: "./html/amidst-the-clouds/index.html", imgSrc: "amidst-the-clouds.webp", name: "Amidst the Clouds" },
	{ href: "./html/avalanche/index.html", imgSrc: "avalanche.webp", name: "Avalanche" },
	{ href: "./html/backrooms/index.html", imgSrc: "backrooms.webp", name: "Backrooms" },
	{ href: "./html/bad-ice-cream/index.html", imgSrc: "bad-ice-cream.webp", name: "Bad Icecream" },
	{ href: "./html/bad-ice-cream-2/index.html", imgSrc: "bad-ice-cream-2.webp", name: "Bad Icecream 2" },
	{ href: "./html/bad-ice-cream-3/index.html", imgSrc: "bad-ice-cream-3.webp", name: "Bad Icecream 3" },
	{ href: "./html/baldis-basics/index.html", imgSrc: "baldis-basics.webp", name: "Baldis Basics" },
	{ href: "./html/ball-hop/index.html", imgSrc: "ballhop.webp", name: "Ballhop" },
	{ href: "./html/ballistic-chickens/index.html", imgSrc: "ballistic-chickens.webp", name: "Ballistic Chickens" },
	{ href: "./html/basketball-stars/index.html", imgSrc: "BAS.webp", name: "Basketball Stars" },
	{ href: "./html/biters-io/index.html", imgSrc: "biters.webp", name: "Biters" },
	{ href: "./html/blocky-tower/index.html", imgSrc: "blocky.webp", name: "Blocky tower" },
	{ href: "./html/bloonstd/index.html", imgSrc: "bloonstd.webp", name: "Bloonstd" },
	{ href: "./html/bloonstd2/index.html", imgSrc: "bloonstd2.webp", name: "Bloonstd 2" },
	{ href: "./html/bloonstd4/index.html", imgSrc: "bloonstd4.webp", name: "Bloonstd 4" },
	{ href: "./html/boxing-physics/index.html", imgSrc: "box.webp", name: "Boxing" },
	{ href: "./html/breakout/index.html", imgSrc: "breakout.webp", name: "Breakout" },
	{ href: "./html/browserquest/index.html", imgSrc: "BrowserQuest.webp", name: "Browserquest" },
	{ href: "./html/big-tower-tiny-square/index.html", imgSrc: "btts.webp", name: "Big Tower Tiny Square" },
	{ href: "./html/circlo/index.html", imgSrc: "circlo.webp", name: "Circlo" },
	{ href: "./html/cluster-rush/index.html", imgSrc: "cluster.webp", name: "Cluster Rush" },
	{ href: "./html/connect3/index.html", imgSrc: "con3.webp", name: "Connect 3" },
	{ href: "./html/core-ball/index.html", imgSrc: "coreball.webp", name: "Coreball" },
	{ href: "./html/crossyroad/index.html", imgSrc: "crossyroad.webp", name: "Crossyroad" },
	{ href: "./html/csgo-clicker/index.html", imgSrc: "CSGO.webp", name: "CSGO Clicker" },
	{ href: "./html/cuttherope/index.html", imgSrc: "ctr.webp", name: "Cut the Rope" },
	{ href: "./html/cupcakes/index.html", imgSrc: "cupcakes.webp", name: "Cupcake 2048" },
	{ href: "./html/cyber-city-driver/index.html", imgSrc: "cyber.webp", name: "Cyber City Driver" },
	{ href: "./html/dogeminer/index.html", imgSrc: "Dogecoin.webp", name: "Dogeminer" },
	{ href: "./html/doodlejump/index.html", imgSrc: "doodle.webp", name: "Doodle Jump" },
	{ href: "./html/drift-city/index.html", imgSrc: "driftc.webp", name: "Drift City" },
	{ href: "./html/driftking/index.html", imgSrc: "driftking.webp", name: "Drift King" },
	{ href: "./html/dunkers-fight/index.html", imgSrc: "dunk.webp", name: "Dunkers Fight" },
	{ href: "./html/eatio/index.html", imgSrc: "eatio.webp", name: "Eatio" },
	{ href: "./html/edge-surf/index.html", imgSrc: "edge-surf.webp", name: "Ede Surf" },
	{ href: "./html/eel-slap/index.html", imgSrc: "eel-slap.webp", name: "Eel Slap" },
	{ href: "./html/eggy-car/index.html", imgSrc: "eggy-car.webp", name: "Eggy Car" },
	{ href: "./html/steal-this-election/index.html", imgSrc: "elec.webp", name: "Steal this Election" },
	{ href: "./html/endlesswar3/index.html", imgSrc: "endlesswar3.webp", name: "Endless War 3" },
	{ href: "./html/evolution/index.html", imgSrc: "evolution.webp", name: "Evolution" },
	{ href: "./html/exo/index.html", imgSrc: "exo.webp", name: "Exo" },
	{ href: "./html/flappyplane/index.html", imgSrc: "flappyplae.jpeg", name: "Flappy Plane" },
	{ href: "./html/fliphero/index.html", imgSrc: "fliphero.webp", name: "Flip Hero" },
	{ href: "./html/fnaf/index.html", imgSrc: "fnaf.webp", name: "FNAF" },
	{ href: "./html/fnaf2/index.html", imgSrc: "fnaf.webp", name: "FNAF 2" },
	{ href: "./html/fnaf3/index.html", imgSrc: "fnaf.webp", name: "FNAF 3" },
	{ href: "./html/fnaf4/index.html", imgSrc: "fnaf.webp", name: "FNAF 4" },
	{ href: "./html/fruitninja/index.html", imgSrc: "fruitninja.webp", name: "Fruit Ninja" },
	{ href: "./html/funnyshooter/index.html", imgSrc: "funnyshooter.webp", name: "Funny Shooter" },
	{ href: "./html/goodnight/index.html", imgSrc: "gn.webp", name: "Goodnight" },
	{ href: "./html/idle-breakout/index.html", imgSrc: "idlebreakout.webp", name: "Idle Breakout" },
	{ href: "./html/impossiblequiz/index.html", imgSrc: "impossiblequiz.webp", name: "Impossible Quiz" },
	{ href: "./html/interactivebuddy/index.html", imgSrc: "interactivebuddy.webp", name: "Interactive Buddy" },
	{ href: "./html/jetpack-joyride/index.html", imgSrc: "jetpack-joyride.webp", name: "Jetpack Joyride" },
	{ href: "./html/just-fall/index.html", imgSrc: "just-fall.webp", name: "Just Fall" },
	{ href: "./html/kitchen-gun-game/index.html", imgSrc: "kitchen-gun-game.webp", name: "Kitchen Gun Game" },
	{ href: "./html/kittencannon/index.html", imgSrc: "kittencannon.webp", name: "Kitten Cannon" },
	{ href: "./html/krunker/index.html", imgSrc: "krunker.webp", name: "Krunker" },
	{ href: "./html/learntofly/index.html", imgSrc: "learntofly.webp", name: "Learn to Fly" },
	{ href: "./html/motox3m-spooky/index.html", imgSrc: "moto-spook.webp", name: "Moto X3M Spooky" },
	{ href: "./html/motox3m-pool/index.html", imgSrc: "motox3m-pool.webp", name: "Moto X3M Pool" },
	{ href: "./html/motox3m-winter/index.html", imgSrc: "motox3m-winter.webp", name: "Moto X3M Winter" },
	{ href: "./html/motox3m/index.html", imgSrc: "motox3m.webp", name: "Moto X3M" },
	{ href: "./html/motox3m2/index.html", imgSrc: "motox3m2.webp", name: "Moto X3M 2" },
	{ href: "./html/2048-multitask/index.html", imgSrc: "multit.webp", name: "2048 Multitask" },
	{ href: "./html/pacman/index.html", imgSrc: "pacman.webp", name: "Pacman" },
	{ href: "./html/paperio/index.html", imgSrc: "paperio.webp", name: "Paper.io" },
	{ href: "./html/papery-planes/index.html", imgSrc: "paperplane.webp", name: "Papery Planes" },
	{ href: "./html/particle-clicker/index.html", imgSrc: "parclick.webp", name: "Particle Clicker" },
	{ href: "./html/picky-package/index.html", imgSrc: "pickyback.webp", name: "Picky Package" },
	{ href: "./html/pokemonfirered/index.html", imgSrc: "PokemonFireRed.webp", name: "Pokemon Fire Red" },
	{ href: "./html/pong/index.html", imgSrc: "pong.webp", name: "Pong" },
	{ href: "./html/racer/index.html", imgSrc: "Racer.webp", name: "Racer" },
	{ href: "./html/retrobowl/index.html", imgSrc: "retrobowl.webp", name: "Retro Bowl" },
	{ href: "./html/rooftop-snipers-2/index.html", imgSrc: "Rooftop-Snipers.webp", name: "Rooftop Snipers" },
	{ href: "./html/sans/index.html", imgSrc: "sans.webp", name: "Sans" },
	{ href: "./html/idle-shark/index.html", imgSrc: "sharkgame.webp", name: "Idle Shark" },
	{ href: "./html/spaceinvaders/index.html", imgSrc: "spaceinv.webp", name: "Space Invaders" },
	{ href: "./html/stack/index.html", imgSrc: "stack.webp", name: "Stack" },
	{ href: "./html/stack-ball/index.html", imgSrc: "stackball.webp", name: "Stack Ball" },
	{ href: "./html/subwaysurferssanfrancisco/index.html", imgSrc: "subsan.webp", name: "Subway Surfers San Fran" },
	{ href: "./html/subwaysurfersbeijing/index.html", imgSrc: "subwaysurferbeijing.webp", name: "Subway Surfers BeiJing" },
	{ href: "./html/subwaysurfershouston/index.html", imgSrc: "subwaysurfershouston.webp", name: "Subway Surfers Houston" },
	{ href: "./html/subwaysurfersmonaco/index.html", imgSrc: "SubwayMonaco.webp", name: "Subway Surfers Monaco" },
	{ href: "./html/temple-run-2/index.html", imgSrc: "templerun.webp", name: "Temple Run 2" },
	{ href: "./html/thesquare/index.html", imgSrc: "thesquare.webp", name: "The Square" },
	{ href: "./html/timeshooter/index.html", imgSrc: "timeshooters.webp", name: "Time Shooters" },
	{ href: "./html/tic-tac-toe/index.html", imgSrc: "toe.webp", name: "Tic-Tac-Toe" },
	{ href: "./html/tic-tac-toe-ai/index.html", imgSrc: "toeai.webp", name: "Tic-Tac-Toe AI" },
	{ href: "./html/towermaster/index.html", imgSrc: "towermaster.webp", name: "Tower Master" },
	{ href: "./html/tunnelrush/index.html", imgSrc: "tunnelrush.webp", name: "Tunnel Rush" },
	{ href: "./html/tv-static/index.html", imgSrc: "tv-static.webp", name: "TV Static" },
	{ href: "./html/veloce/index.html", imgSrc: "VELOCE.webp", name: "Veloce" },
	{ href: "./html/vex3/index.html", imgSrc: "vex3.webp", name: "Vex 3" },
	{ href: "./html/vex4/index.html", imgSrc: "vex4.webp", name: "Vex 4" },
	{ href: "./html/vex5/index.html", imgSrc: "vex5.webp", name: "Vex 5" },
	{ href: "./html/vex6/index.html", imgSrc: "vex6.webp", name: "Vex 6" },
	{ href: "./html/vex7/index.html", imgSrc: "vex7.webp", name: "Vex 7" },
	{ href: "./html/wallsmash/index.html", imgSrc: "wallsmash.webp", name: "Wall Smash" },
	{ href: "./html/waterworks/index.html", imgSrc: "waterworks.webp", name: "Water Works" },
	{ href: "./html/weavesilk/index.html", imgSrc: "weavesilk.webp", name: "Weave Silk" },
	{ href: "./html/webgl-fluid-simulation/index.html", imgSrc: "webgl-fluid-simulation.webp", name: "Fluid Simulation" },
	{ href: "./html/webretro/index.html", imgSrc: "webretro.webp", name: "Web Retro" },
	{ href: "./html/whac-a-mole/index.html", imgSrc: "Whac-A-Mole.webp", name: "Whac-A-Mole" },
	{ href: "./html/worlds-hardest-game/index.html", imgSrc: "whg.webp", name: "World's Hardest Game" },
	{ href: "./html/wordle/index.html", imgSrc: "wordle.webp", name: "Wordle" },
	{ href: "./html/x-trial-racing/index.html", imgSrc: "xtr.webp", name: "X Trial Racing" },
	{ href: "./html/yoshifabrication/index.html", imgSrc: "YFS.webp", name: "Yoshi Fabricator" },
	{ href: "./html/zombs-royale/index.html", imgSrc: "zombs-royale.webp", name: "Zombs Royale" },
	{ href: "./html/zoro/index.html", imgSrc: "zoro.webp", name: "Zoro" },
	{ href: "./html/lozmaker/game/lozmaker.html", imgSrc: "lozmaker.png", name: "Ledegnd of Zelda Maker" },
	{ href: "./html/towerdef.html", imgSrc: "towerdef.png", name: "Tower Defence" },
	{ href: "./html/yetanotherworld.html", imgSrc: "yetanotherworld.png", name: "Yet Another World" },
	{ href: "./html/afterlife/game/afterlife.html", imgSrc: "afterlife.png", name: "Afterlife" },
	{ href: "./html/earthsausage/game/earthsausage.html", imgSrc: "earth.png", name: "Earth Sausage" },
	{ href: "./html/flatguys/game/flatguys.html", imgSrc: "flatguys.png", name: "Flat Guys" },
	{ href: "./html/monke/game/monke.html", imgSrc: "monke.png", name: "Monke" },
	{ href: "./html/pixelbearadventure/game/pixelbearadventure.html", imgSrc: "pixelbearadventure.png", name: "Pixel Bear Adventure" },
	{ href: "./html/pixelspeedrun/game/pixelspeedrun.html", imgSrc: "pixelspeedrun.png", name: "Pixel Speedrun" },
	{ href: "./html/pizzachallenge/game/pizzachallenge.html", imgSrc: "pizzachallenge.png", name: "Pizza Challange" },
	{ href: "./html/retro speed/game/retro speed.html speed.html", imgSrc: "retro speed.png", name: "Retro Speed" },
	{ href: "./html/tank trouble 2.html", imgSrc: "tank trouble 2.png", name: "Tank Trouble 2" },
	{ href: "./html/throwapotato.html", imgSrc: "throwapotato.png", name: "Throw a Potato" },
	{ href: "./html/throwapotato2.html", imgSrc: "throwapotato2.png", name: "Throw a Potato 2" },
	{ href: "./html/throwapotato3.html", imgSrc: "throwapotato3.png", name: "Throw a Potato in Space" },
];
