export default [
	{ href: "./html/throw a potato again/index.html", imgSrc: "throwapotato2.png", name: "Throw a Potato Again" },
	{ href: "./html/throw a potato in space/index.html", imgSrc: "throwapotato3.png", name: "Throw a Potato in Space" },
	{ href: "./html/getaway shootout/index.html", imgSrc: "getaway-shootout.jfif", name: "getaway shootout"},
    { href: './html/tube clicker/index.html', imgSrc: 'tube clicker.jpg', name: 'tube clicker' , 'page': 2},
    { href: './html/crossy cat/game/index.html', imgSrc: 'crossy cat.jpg', name: 'crossy cat' , 'page': 2},
    { href: './swf/twin shot 2/index.html', imgSrc: 'twin shot 2.jpg', name: 'twin shot 2' , 'page': 2},
	{ href: './html/block shooter frenzy/index.html', imgSrc: 'block shooter frenzy.jpg', name: 'block shooter frenzy' , 'page': 2},
  	{ href: './html/three goblets/index.html', imgSrc: 'three goblets.png', name: 'three goblets' , 'page': 2},
  	{ href: './html/super pickleball adventure/index.html', imgSrc: 'super pickleball adventure.png', name: 'super pickleball adventure' , 'page': 2},
  	{ href: './html/squareX/index.html', imgSrc: 'squarex.jpg', name: 'squareX' , 'page': 2},
  	{ href: './html/metrocubevania/index.html', imgSrc: 'metrocubevania.png', name: 'metrocubevania' , 'page': 2},
  	{ href: './html/knightin/index.html', imgSrc: 'knightin.jpg', name: 'knightin' , 'page': 2},
  	{ href: './html/ISLANDER/index.html', imgSrc: 'ISLANDER.png', name: 'ISLANDER' , 'page': 2},
  	{ href: './html/final earth 2/index.html', imgSrc: 'finalearth2.png', name: 'final earth 2' , 'page': 2},
  	{ href: './html/delia the traveling witch/index.html', imgSrc: 'delia the traveling witch.png', name: 'delia the traveling witch' , 'page': 2},
  	{ href: './html/dark tomb/index.html', imgSrc: 'dark tomb.jpg', name: 'dark tomb' , 'page': 2},
  	{ href: './html/another gentlemans adventure/index.html', imgSrc: 'another gentlemans adventure.jpg', name: 'another gentlemans adventure' , 'page': 2},
	{ href: './html/Throw a Potato/index.html', imgSrc: 'Throw a Potato.png', name: 'Throw a Potato' , 'page': 2},
	{ href: './html/westoon/index.html', imgSrc: 'westoon.jpg', name: 'westoon' , 'page': 2},
	{ href: './html/thumb fighter christmas/index.html', imgSrc: 'thumb fighter christmas.jpg', name: 'thumb fighter christmas' , 'page': 2},
	{ href: './html/sink it/index.html', imgSrc: 'sink it.jpg', name: 'sink it' , 'page': 2},
	{ href: './html/minibattles/index.html', imgSrc: 'minibattles.jpg', name: 'minibattles' , 'page': 2},
	{ href: './html/gunspin/index.html', imgSrc: 'gunspin.jpg', name: 'gunspin' , 'page': 2},
	{ href: './html/blocky snakes/index.html', imgSrc: 'blocky snakes.jpg', name: 'blocky snakes' , 'page': 2},
	{ href: './html/tiny heist/index.html', imgSrc: 'tiny heist.jpg', name: 'tiny heist' , 'page': 2},
	{ href: './html/poker/index.html', imgSrc: 'poker.jpg', name: 'poker' , 'page': 2},
	{ href: './html/blackjack/index.html', imgSrc: 'blackjack.jpg', name: 'blackjack' , "page": 2},
	{ href: "./html/leader-strike/index.html", imgSrc: "leader-strike.jfif", name: "leader strike" , "page": 2},
	{ href: './html/we become what we behold/index.html', imgSrc: 'we become what we behold.jpg', name: 'we become what we behold' , "page": 2},
	{ href: './html/idle lumber inc/index.html', imgSrc: 'idle lumber inc.jpg', name: 'idle lumber inc' , "page": 2},
	{ href: './html/idle digging tycoon/index.html', imgSrc: 'idle digging tycoon.jpg', name: 'idle digging tycoon' , "page": 2},
	{ href: './html/bomber royale/index.html', imgSrc: 'bomber royale.jpg', name: 'bomber royale' , "page": 2},
	{ href: './html/blumgi paintball/index.html', imgSrc: 'blumgi paintball.jpg', name: 'blumgi paintball' , "page": 2},
	{ href: "./html/badegg.io/index.html", imgSrc: "badegg.io.jpg", name: "badegg.io" , "page": 2},
	{ href: "./swf/cactus mccoy/index.html", imgSrc: "cactus mccoy.jpg", name: "cactus mccoy" , "page": 2},
	{ href: "./swf/cactus mccoy 2/index.html", imgSrc: "cactus mccoy 2.jpg", name: "cactus mccoy 2" , "page": 2},
	{ href: "./html/terretorial.io/index.html", imgSrc: "terretorial.io.jpeg", name: "terretorial.io" , "page": 2},
	{ href: "./html/just passing 2/index.html", imgSrc: "just passing 2.jpg", name: "just passing 2" , "page": 2},
	{ href: "./swf/jacksmith/index.html", imgSrc: "jacksmith.jpg", name: "jacksmith" , "page": 2},
	{ href: "./html/Pre Civilization Bronze Age/index.html", imgSrc: "Pre Civilization Bronze Age.jpg", name: "Pre Civilization Bronze Age" , "page": 2},
	{ href: "./html/strongdog chat/index.html", imgSrc: "strongdog chat.png", name: "Strongdog Chat" , "page": 2},
	{ href: "./html/shipo.io/index.html", imgSrc: "shipo.io.jpg", name: "shipo.io" , "page": 2},
	{ href: "./html/conq.io/index.html", imgSrc: "conq.io.jpg", name: "conq.io" , "page": 2},
	{ href: "./html/sheep party/index.html", imgSrc: "sheep party.jpg", name: "sheep party" , "page": 2},
	{ href: "./html/friday night funkin/index.html", imgSrc: "friday night funkin.jpg", name: "friday night funkin" , "page": 2},
	{ href: "./html/tanko.io/index.html", imgSrc: "tanko.io.jpg", name: "tanko.io" , "page": 2},
	{ href: "./html/tag/index.html", imgSrc: "tag.jpg", name: "tag" , "page": 2},
	{ href: "./html/level devil/index.html", imgSrc: "level devil.jpg", name: "level devil" , "page": 2},
	{ href: "./html/checkers/index.html", imgSrc: "checkers.png", name: "checkers" , "page": 2},
	{ href: "./html/gladihoppers/index.html", imgSrc: "gladdihoppers.jfif", name: "gladihoppers" , "page": 2},
	{ href: "./html/water color sort/index.html", imgSrc: "water color sort.png", name: "water color sort" , "page": 2},
	{ href: "./html/fireboy and watergirl 6/index.html", imgSrc: "fireboy and watergirl 6.jfif", name: "fireboy and watergirl 6" , "page": 2},
	{ href: "./html/Fireboy and Watergirl 5/index.html", imgSrc: "Fireboy and Watergirl 5.webp", name: "Fireboy and Watergirl 5" , "page": 2},
	{ href: "./html/Fireboy and Watergirl 4/index.html", imgSrc: "Fireboy and Watergirl 4.jfif", name: "Fireboy and Watergirl 4" , "page": 2},
	{ href: "./html/Fireboy and Watergirl 3/index.html", imgSrc: "Fireboy and Watergirl 3.jfif", name: "Fireboy and Watergirl 3" , "page": 2},
	{ href: "./html/Fireboy and Watergirl 2/index.html", imgSrc: "Fireboy and Watergirl 2.jfif", name: "Fireboy and Watergirl 2" , "page": 2},
	{ href: "./html/Fireboy and Watergirl 1/index.html", imgSrc: "Fireboy and Watergirl 1.jfif", name: "Fireboy and Watergirl 1" , "page": 2},
	{ href: "./swf/earn to die/index.html", imgSrc: "earn to die.png", name: "earn to die" , "page": 2},
	{ href: "./html/paper minecraft ender dragon/index.html", imgSrc: "paper minecraft ender dragon.jfif", name: "paper minecraft ender dragon" , "page": 2},
	{ href: "./html/grindcraft/index.html", imgSrc: "grindcraft.jfif", name: "grindcraft" , "page": 2},
	{ href: "./html/pixwars 2/index.html", imgSrc: "pixwars 2.jfif", name: "pixwars 2" , "page": 2},
	{ href: "./swf/strike force heros/index.html", imgSrc: "strke force heros.jfif", name: "strike force heros" , "page": 2},
	{ href: "./swf/burger tycoon/index.html", imgSrc: "burger tycoon.jfif", name: "burger tycoon" , "page": 2},
	{ href: "./swf/miragine war/index.html", imgSrc: "miragine war.jfif", name: "miragine war" , "page": 2},
	{ href: "./html/traffic tour/index.html", imgSrc: "traffic tour.jfif", name: "traffic tour" , "page": 2},
	{ href: "./html/superfighters/index.html", imgSrc: "superfighters.jfif", name: "superfighters" , "page": 2},
	{ href: "./html/super liquid soccer/index.html", imgSrc: "supper liquid soccer.jfif", name: "super liquid soccer" , "page": 2},
	{ href: "./html/spelunky/index.html", imgSrc: "spelunky.jfif", name: "spelunky" , "page": 2},
	{ href: "./html/rabbit samurai 2/index.html", imgSrc: "rabbit samurai 2.jfif", name: "rabbit samurai 2" , "page": 2},
	{ href: "./html/rabbit samurai/index.html", imgSrc: "rabbit samurai.jfif", name: "rabbit samurai" , "page": 2},
	{ href: "./html/quake/index.html", imgSrc: "quake.jfif", name: "quake" , "page": 2},
	{ href: "./html/pizza tower/index.html", imgSrc: "pizza tower.jfif", name: "pizza tower" , "page": 2},
	{ href: "./html/party project/index.html", imgSrc: "party project.jfif", name: "party project" , "page": 2},
	{ href: "./html/onion boy/index.html", imgSrc: "onion boy.jfif", name: "onion boy" , "page": 2},
	{ href: "./html/NG stars/index.html", imgSrc: "NG stars.jfif", name: "NG stars" , "page": 2},
	{ href: "./html/n-gon/index.html", imgSrc: "n-gon.png", name: "n-gon" , "page": 2},
	{ href: "./html/gunnight/index.html", imgSrc: "gunnight.jfif", name: "gunnight" , "page": 2},
	{ href: "./html/freefall tournament/index.html", imgSrc: "freefall tournament.jfif", name: "freefall tournament" , "page": 2},
	{ href: "./html/fighter aircraft piolet/index.html", imgSrc: "fighter aircraft piolet.jfif", name: "fighter aircraft piolet" , "page": 2},
	{ href: "./html/die in the dungeon/index.html", imgSrc: "die in the dungeon.png", name: "die in the dungeon" , "page": 2},
	{ href: "./html/cannon basketball 4/index.html", imgSrc: "cannon basketball.jfif", name: "cannon basketball 4" , "page": 2},
	{ href: "./html/burrito bison/index.html", imgSrc: "burrito bison.jfif", name: "burrito bison" , "page": 2},
	{ href: "./html/bumpyball.io/index.html", imgSrc: "bumpyball.io.jfif", name: "bumpyball.io" , "page": 2},
	{ href: "./html/basket legend 2020/index.html", imgSrc: "basket legend 2020.jfif", name: "basket legend 2020" , "page": 2},
	{ href: "./html/basket and ball/index.html", imgSrc: "basket and ball.jfif", name: "basket and ball" , "page": 2},
	{ href: "./html/adventure drivers/index.html", imgSrc: "adventure drivers.jfif", name: "adventure drivers" , "page": 2},
	{ href: "./html/tank trouble 2/index.html", imgSrc: "tank trouble 2.jfif", name: "tank trouble 2" , "page": 2},
	{ href: "./html/super santa kicker/index.html", imgSrc: "super santa kicker.png", name: "super santa kicker" , "page": 2},
	{ href: "./html/solitaire/index.html", imgSrc: "solitaire.jfif", name: "solitaire" , "page": 2},
	{ href: "./html/nitroclash.io/index.html", imgSrc: "nitroclash.io.jfif", name: "nitroclash.io" , "page": 2},
	{ href: "./html/gravity soccer/index.html", imgSrc: "gravity soccer.jfif", name: "gravity soccer" , "page": 2},
	{ href: "./html/going balls/index.html", imgSrc: "going balls.jfif", name: "going balls" , "page": 2},
	{ href: "./html/falling fox/index.html", imgSrc: "falling fox.jfif", name: "falling fox" , "page": 2},
	{ href: "./html/draw the hill/index.html", imgSrc: "draw the hill.jfif", name: "draw the hill" , "page": 2},
	{ href: "./html/color switch/index.html", imgSrc: "color switch.png", name: "color switch" , "page": 2},
	{ href: "./html/brawlguys.io/index.html", imgSrc: "brawlguys.io.jfif", name: "brawlguys.io" , "page": 2},
	{ href: "./html/basketbros.io/index.html", imgSrc: "basketbros.io.jfif", name: "basketbros.io" , "page": 2},
	{ href: "./html/ballistic/index.html", imgSrc: "ballistic.jfif", name: "ballistic" , "page": 2},
	{ href: "./html/two-punk-racing/index.html", imgSrc: "two-punk-racing.jfif", name: "two punk racing" , "page": 2},
	{ href: "./html/tube-jumpers/index.html", imgSrc: "tube-jumpers.jfif", name: "tube jumpers" , "page": 2},
	{ href: "./html/tomb-of-the-mask/index.html", imgSrc: "toumb-of-the-mask.png", name: "tomb of the mask" , "page": 2},
	{ href: "./html/tank-io/index.html", imgSrc: "tank.io.png", name: "tank.io" , "page": 2},
	{ href: "./html/supra-speed-racing-turbo-drift/index.html", imgSrc: "supra-speed-racing-turbo-drift.jfif", name: "racing turbo drift" , "page": 2},
	{ href: "./html/sports/index.html", imgSrc: "sports.png", name: "sports" , "page": 2},
	{ href: "./html/sonic-revert/index.html", imgSrc: "sonic-revert.jfif", name: "sonic revert" , "page": 2},
	{ href: "./html/pixelfoosball/index.html", imgSrc: "pixel-foosball.jfif", name: "pixel foosball" , "page": 2},
	{ href: "./html/Penguinio/index.html", imgSrc: "penguin-io.jfif", name: "Penguin.io" , "page": 2},
	{ href: "./html/novabilliards/index.html", imgSrc: "nova-billiards.jfif", name: "nova billiards" , "page": 2},
	{ href: "./html/madalin-cars/index.html", imgSrc: "madalin-cars.jfif", name: "madalin cars" , "page": 2},
	{ href: "./html/kart-fight-io/index.html", imgSrc: "kart-fight-io.jfif", name: "kart fight.io" , "page": 2},
	{ href: "./html/gungame-shooting-warfare-blocky-gangster/index.html", imgSrc: "gungame-shooting-warfare-blocky-gangster.jfif", name: "blocky gangster" , "page": 2},
	{ href: "./html/grab-party-io/index.html", imgSrc: "grab-party-io.jfif", name: "grab party.io" , "page": 2},
	{ href: "./html/dunkers/index.html", imgSrc: "dunkers.png", name: "dunkers" , "page": 2},
	{ href: "./html/drift/index.html", imgSrc: "drift.jfif", name: "drift" , "page": 2},
	{ href: "./html/doomz-io/index.html", imgSrc: "doomz-io.jfif", name: "doomz.io" , "page": 2},
	{ href: "./html/discus/index.html", imgSrc: "discus.jfif", name: "disc us" , "page": 2},
	{ href: "./html/death-run-3d/index.html", imgSrc: "death-run-3d.jfif", name: "death run 3d" , "page": 2},
	{ href: "./html/cube-flip/index.html", imgSrc: "cube-flip.jfif", name: "cube flip" , "page": 2},
	{ href: "./html/crazy-pixel-apocalypse-3/index.html", imgSrc: "crazy-pixel-apocalypse-3.jfif", name: "pixel apocalypse" , "page": 2},
	{ href: "./html/cleanupio/index.html", imgSrc: "cleanupio.jfif", name: "cleanup.io" , "page": 2},
	{ href: "./html/call-of-ops-2/index.html", imgSrc: "call-of-ops-2.jfif", name: "call of ops 2" , "page": 2},
	{ href: "./html/blocky-gun-paintball-3/index.html", imgSrc: "blocky-gun-paintball-3.jfif", name: "blocky gun paintball" , "page": 2},
	{ href: "./html/basketball_io/index.html", imgSrc: "basketball_io.jfif", name: "basketball.io" , "page": 2},
	{ href: "./html/baseballfury/index.html", imgSrc: "baseballfury.jfif", name: "baseball fury" , "page": 2},
	{ href: "./html/ball-mayhem/index.html", imgSrc: "ball-mayhem.png", name: "ball mayhem" , "page": 2},
	{ href: "./html/adofai/index.html", imgSrc: "adofai.png", name: "A Dance of Fire And Ice" , "page": 2},
	{ href: "./html/sleepy knight/index.html", imgSrc: "sleepy knight.png", name: "sleepy knight" , "page": 2},
	{ href: "./html/greedy mimic/index.html", imgSrc: "greedy mimic.png", name: "greedy mimic" , "page": 2},
	{ href: "./html/sticky sorcerer/index.html", imgSrc: "sticky sourcerer.png", name: "sticky sourcerer" , "page": 2},
	{ href: "./html/yarne/index.html", imgSrc: "yarne.png", name: "yarne" , "page": 2},
	{ href: "./html/two timin towers/index.html", imgSrc: "two timin towers.jpg", name: "two timin towers" , "page": 2},
	{ href: "./html/slimoban 2/index.html", imgSrc: "slimoban 2.jpg", name: "slimoban 2" , "page": 2},
	{ href: "./html/slide fill/index.html", imgSrc: "slide fill.jpg", name: "slide fill" , "page": 2},
	{ href: "./html/sheep/index.html", imgSrc: "sheep.png", name: "sheep" , "page": 2},
	{ href: "./html/roll merge 3d/index.html", imgSrc: "roll merge 3d.jpg", name: "roll merge 3d" , "page": 2},
	{ href: "./html/ordeals of december/index.html", imgSrc: "ordeals of december.jpg", name: "ordeals of december" , "page": 2},
	{ href: "./html/one screen run 2/index.html", imgSrc: "one screen run 2.png", name: "one screen run 2" , "page": 2},
	{ href: "./html/indestructotank gb/index.html", imgSrc: "indestructotank gb.jpg", name: "indestructotank gb" , "page": 2},
	{ href: "./html/gaia/index.html", imgSrc: "gaia.webp", name: "gaia" , "page": 2},
	{ href: "./html/bokdown/index.html", imgSrc: "bokdown.png", name: "bokdown" , "page": 2},
	{ href: "./html/yin and yang/index.html", imgSrc: "yin and yang.jpg", name: "yin and yang" , "page": 2},
	{ href: "./html/top outpost/index.html", imgSrc: "top outpost.jpg", name: "top outpost" , "page": 2},
	{ href: "./html/spirit dungeons/index.html", imgSrc: "spirit dungeons.webp", name: "spirit dungeons" , "page": 2},
	{ href: "./html/pixel tap dungeon/index.html", imgSrc: "pixel tap dungeon.png", name: "pixel tap dungeon" , "page": 2},
	{ href: "./html/out of ctrl/index.html", imgSrc: "out of ctrl.jpg", name: "out of ctrl" , "page": 2},
	{ href: "./html/mad pirate skeleton/index.html", imgSrc: "mad pirate skeleton.jpg", name: "mad pirate skeleton" , "page": 2},
	{ href: "./html/kity builder prototype/index.html", imgSrc: "kity builder prototype.png", name: "kity builder prototype" , "page": 2},
	{ href: "./html/jetscout boot camp/index.html", imgSrc: "jetscout boot camp.png", name: "jetscout boot camp" , "page": 2},
	{ href: "./html/idle fill factory/index.html", imgSrc: "idle fill factory.jpg", name: "idle fill factory" , "page": 2},
	{ href: "./html/find a way out/index.html", imgSrc: "find a way out.jpg", name: "find a way out" , "page": 2},
	{ href: "./html/cursed travels flame of the banshee/index.html", imgSrc: "cursed travels flame of the banshee.png", name: "cursed travels flame of the banshee" , "page": 2},
	{ href: "./html/cognite/index.html", imgSrc: "cognite.jpg", name: "cognite" , "page": 2},
	{ href: "./html/white pen road/index.html", imgSrc: "white pen road.webp", name: "white pen road" , "page": 2},
	{ href: "./html/space cowboy/index.html", imgSrc: "space cowboy.jpg", name: "space cowboy" , "page": 2},
	{ href: "./html/rail connect/index.html", imgSrc: "rail connect.jpg", name: "rail connect" , "page": 2},
	{ href: "./html/put a ring on it/index.html", imgSrc: "put a ring on it.jpg", name: "put a ring on it" , "page": 2},
	{ href: "./html/mutual destruction/index.html", imgSrc: "mutual destruction.jpg", name: "mutual destruction" , "page": 2},
	{ href: "./html/mini bubbles/index.html", imgSrc: "mini bubbles.jpg", name: "mini bubbles" , "page": 2},
	{ href: "./html/leapoid/index.html", imgSrc: "leapoid.jpg", name: "leapoid" , "page": 2},
	{ href: "./html/keyholder/index.html", imgSrc: "keyholder.jpg", name: "keyholder" , "page": 2},
	{ href: "./html/icy north/index.html", imgSrc: "icy north.png", name: "icy north" , "page": 2},
	{ href: "./html/evolutionary psychol/index.html", imgSrc: "evolutionary psychology.jpg", name: "evolutionary psychol" , "page": 2},
	{ href: "./html/escape kid/index.html", imgSrc: "escape kid.webp", name: "escape kid" , "page": 2},
	{ href: "./html/cursed travels the shattered labyrinth/index.html", imgSrc: "cursed travels the shattered labyrinth.png", name: "cursed travels the shattered labyrinth" , "page": 2},
	{ href: "./html/crystal wizards/index.html", imgSrc: "crystal wizards.jpg", name: "crystal wizards" , "page": 2},
	{ href: "./html/calturin/index.html", imgSrc: "calturin.jpg", name: "calturin" , "page": 2},
	{ href: "./html/binary/index.html", imgSrc: "binary.png", name: "binary" , "page": 2},
	{ href: "./html/are you human/index.html", imgSrc: "are you human.webp", name: "are you human" , "page": 2},
	{ href: "./html/anyek the keyboard puzzle/index.html", imgSrc: "anyek the keyboard puzzle.jpg", name: "anyek the keyboard puzzle" , "page": 2},
	{ href: "./html/adventure boy jailbreak/index.html", imgSrc: "adventure boy jailbreak.jpg", name: "adventure boy jailbreak" , "page": 2},
	{ href: "./swf/the impossible quiz 2/index.html", imgSrc: "the impossible quiz 2.avif", name: "the impossible quiz 2" , "page": 2},
	{ href: "./html/shaky structure/index.html", imgSrc: "shaky structure.webp", name: "shaky structure" , "page": 2},
	{ href: "./html/orb of creation/index.html", imgSrc: "orb of creation.jpg", name: "orb of creation" , "page": 2},
	{ href: "./html/incub8/index.html", imgSrc: "incub8.png", name: "incub8" , "page": 2},
	{ href: "./html/tryh4rd/index.html", imgSrc: "tryh4rd.jpg", name: "tryh4rd" , "page": 2},
	{ href: "./html/runick/index.html", imgSrc: "runick.jpg", name: "runick" , "page": 2},
	{ href: "./html/laqueus escape chapter 5/index.html", imgSrc: "laqueus escape chapter 5.jpg", name: "laqueus escape chapter 5" , "page": 2},
	{ href: "./html/drag box/index.html", imgSrc: "drag box.jpg", name: "drag box" , "page": 2},
	{ href: "./html/cloudhopper/index.html", imgSrc: "cloudhopper.webp", name: "cloudhopper" , "page": 2},
	{ href: "./html/yarn untangled/index.html", imgSrc: "yarn untangled.jpg", name: "yarn untangled" , "page": 2},
	{ href: "./html/towerland/index.html", imgSrc: "towerland.jpg", name: "towerland" , "page": 2},
	{ href: "./html/the mage/index.html", imgSrc: "the mage.jpg", name: "the mage" , "page": 2},
	{ href: "./html/telepobox 2/index.html", imgSrc: "telepobox2.jpg", name: "telepobox 2" , "page": 2},
	{ href: "./html/snail trail/index.html", imgSrc: "snail trail.webp", name: "snail trail" , "page": 2},
	{ href: "./html/robox/index.html", imgSrc: "robox.jpg", name: "robox" , "page": 2},
	{ href: "./html/reel deep/index.html", imgSrc: "reel deep.webp", name: "reel deep" , "page": 2},
	{ href: "./html/planet d4rk/index.html", imgSrc: "planet d4rk.png", name: "planet d4rk" , "page": 2},
	{ href: "./html/moosha/index.html", imgSrc: "moosha.jpg", name: "moosha" , "page": 2},
	{ href: "./html/may i have your attention, please/index.html", imgSrc: "may i have your attention, please.png", name: "may i have your attention, please" , "page": 2},
	{ href: "./html/laqueus escape chapter 6/index.html", imgSrc: "laqueus escape chapter 6.avif", name: "laqueus escape chapter 6" , "page": 2},
	{ href: "./html/house pusher/index.html", imgSrc: "house pusher.png", name: "house pusher" , "page": 2},
	{ href: "./html/gobo desert of cubes/index.html", imgSrc: "gobo desert of cubes.jpg", name: "gobo desert of cubes" , "page": 2},
	{ href: "./html/forward winds/index.html", imgSrc: "forward winds.png", name: "forward winds" , "page": 2},
	{ href: "./html/fluctuoid/index.html", imgSrc: "fluctuoid.webp", name: "fluctuoid" , "page": 2},
	{ href: "./html/cursed travels a forgotten seal/index.html", imgSrc: "cursed travels a forgotten seal.png", name: "cursed travels a forgotten seal" , "page": 2},
	{ href: "./html/blacken slash demo/index.html", imgSrc: "blacken slash.jpg", name: "blacken slash demo" , "page": 2},
	{ href: "./html/magirune/index.html", imgSrc: "magirune.jpg", name: "magirune" , "page": 2},
	{ href: "./html/logica emotica/index.html", imgSrc: "logica emotica.jpg", name: "logica emotica" , "page": 2},
	{ href: "./html/hall of palettes/index.html", imgSrc: "hall of palettes.png", name: "hall of palettes" , "page": 2},
	{ href: "./html/nova cloudwalkers/index.html", imgSrc: "nova cloudwalkers.jpg", name: "nova cloudwalkers" , "page": 2},
	{ href: "./html/notebook jam/index.html", imgSrc: "notebook jam.jpg", name: "notebook jam" , "page": 2},
	{ href: "./html/gods of defense/index.html", imgSrc: "gods of defense.jpg", name: "gods of defense" , "page": 2},
	{ href: "./html/slide box/index.html", imgSrc: "slide box.png", name: "slide box" , "page": 2},
	{ href: "./html/sector 01/index.html", imgSrc: "sector 01.jpg", name: "sector 01" , "page": 2},
	{ href: "./html/erase box/index.html", imgSrc: "erase box.jpg", name: "erase box" , "page": 2},
	{ href: "./html/sum lines/index.html", imgSrc: "sum lines.webp", name: "sum lines" , "page": 2},
	{ href: "./html/strg snek/index.html", imgSrc: "strg snek.png", name: "strg snek" , "page": 2},
	{ href: "./html/rotate box/index.html", imgSrc: "rotate box.jpg", name: "rotate box" , "page": 2},
	{ href: "./html/red scarf platformer/index.html", imgSrc: "red scarf platformer.jpg", name: "red scarf platformer" , "page": 2},
	{ href: "./html/peeper reaper/index.html", imgSrc: "peeper reaper.jpg", name: "peeper reaper" , "page": 2},
	{ href: "./html/ninja auto run/index.html", imgSrc: "ninja auto run.webp", name: "ninja auto run" , "page": 2},
	{ href: "./html/murder is game over/index.html", imgSrc: "murder is game over.jpg", name: "murder is game over" , "page": 2},
	{ href: "./html/mirror wizard/index.html", imgSrc: "mirror wizard.jpg", name: "mirror wizard" , "page": 2},
	{ href: "./html/mini swim/index.html", imgSrc: "mini swim.jpg", name: "mini swim" , "page": 2},
	{ href: "./html/mini flips/index.html", imgSrc: "mini flips.jpg", name: "mini flips" , "page": 2},
	{ href: "./html/marcus osnail/index.html", imgSrc: "marcus osnail.png", name: "marcus osnail" , "page": 2},
	{ href: "./html/knights blade/index.html", imgSrc: "knights blade.webp", name: "knights blade" , "page": 2},
	{ href: "./html/infinite night the cunning princess/index.html", imgSrc: "infinite night the cunning princess.jpg", name: "infinite night the cunning princess" , "page": 2},
	{ href: "./html/in space/index.html", imgSrc: "in space.jpg", name: "in space" , "page": 2},
	{ href: "./html/hummin out/index.html", imgSrc: "hummin out.webp", name: "hummin out" , "page": 2},
	{ href: "./html/haunted rooms/index.html", imgSrc: "haunted rooms.webp", name: "haunted rooms" , "page": 2},
	{ href: "./html/darkraid delilah/index.html", imgSrc: "darkraid delilah.jpg", name: "darkraid delilah" , "page": 2},
	{ href: "./html/cordovan/index.html", imgSrc: "cordovan.webp", name: "cordovan" , "page": 2},
	{ href: "./html/contractomaton/index.html", imgSrc: "contractomaton.jpg", name: "contractomaton" , "page": 2},
	{ href: "./html/arrow box/index.html", imgSrc: "arrow box.webp", name: "arrow box" , "page": 2},
	{ href: "./html/viscous ventures/index.html", imgSrc: "viscous ventures.jpg", name: "viscous ventures" , "page": 2},
	{ href: "./html/steel and claw/index.html", imgSrc: "steel and claw.png", name: "steel and claw" , "page": 2},
	{ href: "./html/slime knight/index.html", imgSrc: "slime knight.avif", name: "slime knight" , "page": 2},
	{ href: "./html/platformation/index.html", imgSrc: "platformation.jpg", name: "platformation" , "page": 2},
	{ href: "./html/path of arrows/index.html", imgSrc: "path of arrows.jpg", name: "path of arrows" , "page": 2},
	{ href: "./html/ninja kite/index.html", imgSrc: "ninja kite.jpg", name: "ninja kite" , "page": 2},
	{ href: "./html/mutato potato/index.html", imgSrc: "mutato potato.avif", name: "mutato potato" , "page": 2},
	{ href: "./html/mini rocket/index.html", imgSrc: "mini rocket.avif", name: "mini rocket" , "page": 2},
	{ href: "./html/magnet master redux/index.html", imgSrc: "magnet master redux.jpg", name: "magnet master redux" , "page": 2},
	{ href: "./html/inversion/index.html", imgSrc: "inversion.jpg", name: "inversion" , "page": 2},
	{ href: "./html/handle/index.html", imgSrc: "handle.jpg", name: "handle" , "page": 2},
	{ href: "./html/dispersal vectors/index.html", imgSrc: "dispersal vectors.jpg", name: "dispersal vectors" , "page": 2},
	{ href: "./html/cata catapult/index.html", imgSrc: "cata catapult.png", name: "cata catapult" , "page": 2},
	{ href: "./html/astro steve adventure/index.html", imgSrc: "astro steve adventure.jpg", name: "astro steve adventure" , "page": 2},
	{ href: "./swf/elephant rave 2/index.html", imgSrc: "elephant rave 2.webp", name: "elephant rave 2" , "page": 2},
	{ href: "./html/the designer/index.html", imgSrc: "the designer.jpg", name: "the designer" , "page": 2},
	{ href: "./html/stress chess/index.html", imgSrc: "stress chess.jpg", name: "stress chess" , "page": 2},
	{ href: "./html/specters of the sun/index.html", imgSrc: "specters of the sun.jpg", name: "specters of the sun" , "page": 2},
	{ href: "./html/space order mine/index.html", imgSrc: "space order mine.jpg", name: "space order mine" , "page": 2},
	{ href: "./html/scraplegs/index.html", imgSrc: "scraplegs.webp", name: "scraplegs" , "page": 2},
	{ href: "./html/last plant on earth/index.html", imgSrc: "last plant on earth.webp", name: "last plant on earth" , "page": 2},
	{ href: "./html/gloop/index.html", imgSrc: "gloop.webp", name: "gloop" , "page": 2},
	{ href: "./html/doubleup/index.html", imgSrc: "doubleup.webp", name: "doubleup" , "page": 2},
	{ href: "./html/toms trial/index.html", imgSrc: "toms trial.jpg", name: "toms trial" , "page": 2},
	{ href: "./html/knights blade/index.html", imgSrc: "knights blade.webp", name: "knights blade" , "page": 2},
	{ href: "./html/jetpack kiwi/index.html", imgSrc: "jetpack kiwi.jpg", name: "jetpack kiwi" , "page": 2},
	{ href: "./html/dungeon scroller/index.html", imgSrc: "dongeon scroller.jpg", name: "dungeon scroller" , "page": 2},
	{ href: "./html/a maniac/index.html", imgSrc: "a maniac.webp", name: "a maniac" , "page": 2},
	{ href: "./html/pixelshooter/index.html", imgSrc: "pixelshooter.jpeg", name: "Pixel shooter" , "page": 2},
	{ href: "./html/polytrack/index.html", imgSrc: "polytrack.jfif", name: "Poly track" , "page": 2},
	{ href: "./html/retro bowl college/index.html", imgSrc: "retro bowl college.png", name: "retro bowl college" , "page": 2},
	{ href: "./html/jptragar/web/index.html", imgSrc: "agar.jpeg", name: "agar.io" , "page": 2},
	{ href: "./html/giraffe/index.html", imgSrc: "giraffe.png", name: "giraffes volleyball" , "page": 2},
	{ href: "./swf/duck life tresure hunt/index.html", imgSrc: "duck life tresure hunt.png", name: "duck life tresure hunt" , "page": 2},
	{ href: "./html/un evergreen/index.html", imgSrc: "un evergreen.png", name: "un evergreen" , "page": 2},
	{ href: "./html/super gauntlent/index.html", imgSrc: "super gauntlent.jpg", name: "super gauntlent" , "page": 2},
	{ href: "./html/slis/index.html", imgSrc: "slis.webp", name: "slis" , "page": 2},
	{ href: "./html/mini magbot/index.html", imgSrc: "mini magbot.jpg", name: "mini magbot" , "page": 2},
	{ href: "./html/driftmania/index.html", imgSrc: "driftmania.png", name: "driftmania" , "page": 2},
	{ href: "./html/club tycoon/index.html", imgSrc: "club tycoon.jpg", name: "club tycoon" , "page": 2},
	{ href: "./html/blasting marbles/index.html", imgSrc: "blasting marbles.jpg", name: "blasting marbles" , "page": 2},
	{ href: "./html/deepest sword/index.html", imgSrc: "deepest sword.jpg", name: "deepest sword" , "page": 2},
	{ href: "./html/sort the court/index.html", imgSrc: "sort the court.jpg", name: "sort the court" , "page": 2},
	{ href: "./html/resent/Resent-4.0-Patch-2-English.html", imgSrc: "resent.png", name: "Resent client (mc)" , "page": 2},
	{ href: "./html/yohoho.io/index.html", imgSrc: "yohoho.io.jfif", name: "yohoho.io" },
	{ href: "./html/smash karts/index.html", imgSrc: "smash karts.avif", name: "Smash Karts" },
	{ href: "./html/pathfinder/index.html", imgSrc: "Screenshot 2024-07-09 144933.png", name: "Pathfinder" },
	{ href: "./html/ovo/index.html", imgSrc: "ovo.png", name: "Ovo" },
	{ href: "./html/hasty shaman/index.html", imgSrc: "hasty shaman.png", name: "Hasty Shaman" },
	{ href: "./html/one trick mage/index.html", imgSrc: "one trick mage.png", name: "One Trick Mage" },
	{ href: "./swf/arcuz/base.html", imgSrc: "arcuz.jpg", name: "Arcuz" },
	{ href: "./swf/age of war/base.html", imgSrc: "age of war.jpg", name: "Age of war" },
	{ href: "./html/winter gifts/index.html", imgSrc: "winter gifts.jpg", name: "Winter Gifts" },
	{ href: "./html/tough growth/index.html", imgSrc: "tough growth.jpg", name: "Tough Growth" },
	{ href: "./html/the dark one/index.html", imgSrc: "the dark one.jpg", name: "The Dark One" },
	{ href: "./html/tactical weapon pack/index.html", imgSrc: "tactical weapon pack.png", name: "Tactical Weapon Pack" },
	{ href: "./html/soul mirror/index.html", imgSrc: "soul mirror.jpg", name: "Soul Mirror" },
	{ href: "./html/push/index.html", imgSrc: "push.jpg", name: "Push" },
	{ href: "./html/progress knight/index.html", imgSrc: "progress knight.png", name: "Progress Knight" },
	{ href: "./html/pe norie/index.html", imgSrc: "pe norie.jpg", name: "Pe Norie" },
	{ href: "./html/orange/index.html", imgSrc: "orange.png", name: "Orange" },
	{ href: "./html/mini sticky/index.html", imgSrc: "mini sticky.avif", name: "Mini Sticky" },
	{ href: "./html/mini jumps/index.html", imgSrc: "mini jumps.png", name: "Mini Jumps" },
	{ href: "./html/life in the static/index.html", imgSrc: "life in the static.jpg", name: "Life in the Static" },
	{ href: "./html/laqueus escape chapter 1/index.html", imgSrc: "laqueus escape chapter 1.avif", name: "Laqueus Escape Chapter 1" },
	{ href: "./html/just passing/index.html", imgSrc: "just passing.png", name: "Just Passing" },
	{ href: "./html/hexa knot/index.html", imgSrc: "hexa knot.png", name: "Hexa Knot" },
	{ href: "./html/goodbye doggy/index.html", imgSrc: "goodbye doggy.jpg", name: "Goodbye Doggy" },
	{ href: "./html/generic fishing game/index.html", imgSrc: "generic fishing game.png", name: "Generic Fishing Game" },
	{ href: "./html/dubstep raven/index.html", imgSrc: "dubstep raven.png", name: "Dubstep Raven" },
	{ href: "./html/doodle alive/index.html", imgSrc: "doodle alive.jpg", name: "Doodle Alive" },
	{ href: "./html/detective bass fish/index.html", imgSrc: "detective bass fish.webp", name: "Detective Bass Fish" },
	{ href: "./html/cursed travels below/index.html", imgSrc: "cursed travels below.png", name: "Cursed Travels Below" },
	{ href: "./html/clickventure castaway/index.html", imgSrc: "clickventure castaway.jpg", name: "Clickventure Castaway" },
	{ href: "./html/choppy orc/index.html", imgSrc: "choppy orc.jpg", name: "Choppy Orc" },
	{ href: "./html/cataractae/index.html", imgSrc: "cataractae.jpg", name: "Cataractae" },
	{ href: "./html/cat house/index.html", imgSrc: "cat house.avif", name: "Cat House" },
	{ href: "./html/cardinal chains/index.html", imgSrc: "cardinal chains.png", name: "Cardinal Chains" },
	{ href: "./html/bunnies carrot/index.html", imgSrc: "bunnies carrot.jpg", name: "Bunnies Carrot" },
	{ href: "./html/aspiring artist/index.html", imgSrc: "aspiring artist.webp", name: "Aspiring Artist" },
	{ href: "./html/arcade wizard/index.html", imgSrc: "arcade wizard.png", name: "Arcade Wizard" },
	{ href: "./html/ant art tycoon/index.html", imgSrc: "ant art tycoon.png", name: "Ant Art Tycoon" },
	{ href: "./swf/swords and souls/base.html", imgSrc: "swords and souls.avif", name: "Swords and Souls" },
	{ href: "./swf/sonny2/base.html", imgSrc: "sonny2.jpg", name: "Sonny2" },
	{ href: "./swf/sonny/base.html", imgSrc: "sonny.png", name: "Sonny" },
	{ href: "./swf/kingdom rush frontie/base.html", imgSrc: "kingdom rush frontie.jpg", name: "Kingdom Rush Frontie" },
	{ href: "./swf/kingdom rush/base.html", imgSrc: "kingdom rush.jpg", name: "Kingdom Rush" },
	{ href: "./html/worlds within worlds/index.html", imgSrc: "worlds within worlds.png", name: "Worlds Within Worlds" },
	{ href: "./html/unloop/index.html", imgSrc: "unloop.jpg", name: "Unloop" },
	{ href: "./html/tower of the scorche/index.html", imgSrc: "tower of the scorche.png", name: "Tower of the Scorche" },
	{ href: "./html/there is no game/index.html", imgSrc: "there is no game.jpg", name: "There is No Game" },
	{ href: "./html/scalak/index.html", imgSrc: "scalak.jpg", name: "Scalak" },
	{ href: "./html/sabotage/index.html", imgSrc: "sabotage.webp", name: "Sabotage" },
	{ href: "./html/roots/index.html", imgSrc: "roots.jpg", name: "Roots" },
	{ href: "./html/rogue fable/index.html", imgSrc: "rogue fable.jpg", name: "Rogue Fable" },
	{ href: "./html/pixoji/index.html", imgSrc: "pixoji.png", name: "Pixoji" },
	{ href: "./html/pink/index.html", imgSrc: "pink.png", name: "Pink" },
	{ href: "./html/knight errant/index.html", imgSrc: "knight errant.png", name: "Knight Errant" },
	{ href: "./html/hexologic/index.html", imgSrc: "hexlogic.jpg", name: "Hexologic" },
	{ href: "./html/gragyriss/index.html", imgSrc: "gragyriss.avif", name: "Gragyriss" },
	{ href: "./html/gem twins/index.html", imgSrc: "gem twins.png", name: "Gem Twins" },
	{ href: "./html/dinogen arena/index.html", imgSrc: "dinogen arena.webp", name: "Ginogen Arena" },
	{ href: "./html/cursed travels flame/index.html", imgSrc: "cursed travels flame.png", name: "Cursed Travels Flame" },
	{ href: "./html/clickventure/index.html", imgSrc: "clickbenture.jpg", name: "Clickventure" },
	{ href: "./html/blue/index.html", imgSrc: "blue.png", name: "Blue" },
	{ href: "./html/beam/index.html", imgSrc: "beam.png", name: "Beam" },
	{ href: "./html/a grim love tale/index.html", imgSrc: "a grim love tale.jpg", name: "A Grim Love Tale" },
	{ href: "./html/a grim chase/index.html", imgSrc: "a grim chase.jpg", name: "A Grim Chase" },
	{ href: "./html/babel tower/index.html", imgSrc: "Babel tower.avif", name: "Babel Tower" },
	{ href: "./html/tavern master/index.html", imgSrc: "tavern master.png", name: "Tavern Master" },
	{ href: "./html/green/index.html", imgSrc: "green.png", name: "Green" },
	{ href: "./swf/stealing the diamond/base.html", imgSrc: "stealing the diamond.jpg", name: "Stealing the Diamond" },
	{ href: "./swf/infiltrating the airship/base.html", imgSrc: "infiltrating the airship.jpg", name: "Infiltrating the Airship" },
	{ href: "./swf/fleeing the complex/base.html", imgSrc: "fleeing the complex.jpg", name: "Fleeing the Complex" },
	{ href: "./swf/escaping the prison/base.html", imgSrc: "escaping the pirson.jpg", name: "Escaping the Prison" },
	{ href: "./swf/breaking the bank/base.html", imgSrc: "breaking the bank.jpg", name: "Breaking the Bank" },
	{ href: "./html/tanuki sunset/index.html", imgSrc: "tanuki sunset.jpg", name: "Tanuki Sunset" },
	{ href: "./html/Soccer Random/index.html", imgSrc: "Soccor Random.avif", name: "Soccer Random" },
	{ href: "./html/ricochet arrow/index.html", imgSrc: "ricochet arrow.jpg", name: "Ricochet Arrow" },
	{ href: "./html/Pixel Battles/index.html", imgSrc: "Pixel Battles.jpg", name: "Pixel Battles" },
	{ href: "./html/oil race/index.html", imgSrc: "oil race.avif", name: "Oil Race" },
	{ href: "./html/Mountain Biking/index.html", imgSrc: "Mountain Biking.jpg", name: "Mountain Biking" },
	{ href: "./html/monkey mart/index.html", imgSrc: "monkey mart.png", name: "Monkey Mart" },
	{ href: "./html/maptroid/index.html", imgSrc: "maptroid.jpg", name: "Maptroid" },
	{ href: "./html/hover racer drive/index.html", imgSrc: "hover racer drive.png", name: "Hover Racer Drive" },
	{ href: "./html/hole.io/index.html", imgSrc: "hole.io.jpg", name: "Hole.io" },
	{ href: "./html/erase box/index.html", imgSrc: "erase box.jpg", name: "Erase Box" },
	{ href: "./html/Basket Random/index.html", imgSrc: "Basket Random.jpg", name: "Basket Random" },
	{ href: "./swf/gun mayhem 2/base.html", imgSrc: "gun mayhem 2.jpg", name: "Gun Mayhem 2" },
	{ href: "./html/shortcut race/index.html", imgSrc: "shortcut race.jpg", name: "Shortcut Race" },
	{ href: "./swf/alienthief/base.html", imgSrc: "alienthief.jpg", name: "Alien Theif" },
	{ href: "./swf/checkpoint/base.html", imgSrc: "checkpoint.jpg", name: "Checkpoint" },
	{ href: "./swf/chimneytrouble/base.html", imgSrc: "chimneytrouble.jpg", name: "Chimney Trouble" },
	{ href: "./swf/diasterwillstrike/base.html", imgSrc: "disasterwillstrike.jpg", name: "Disaster Will Strike" },
	{ href: "./swf/drakeandthewizards/base.html", imgSrc: "drakeandthewizards.jpg", name: "Drake and the Wizards" },
	{ href: "./swf/electricman2/base.html", imgSrc: "electricman2.jpg", name: "Electric Man 2" },
	{ href: "./swf/freegear/base.html", imgSrc: "freegear.jpg", name: "Freegear" },
	{ href: "./swf/gooballs/base.html", imgSrc: "gooballs.jpg", name: "Gooballs" },
	{ href: "./swf/hoshisaga1/base.html", imgSrc: "hoshisaga1.png", name: "Hoshi Saga 1" },
	{ href: "./swf/hoshisaga2/base.html", imgSrc: "hoshisaga2.jpg", name: "Hoshi Saga 2" },
	{ href: "./swf/hoshisaga3/base.html", imgSrc: "hoshisaga3.jpg", name: "Hoshi Saga 3" },
	{ href: "./swf/iqball/base.html", imgSrc: "iqball.jpg", name: "IQ Ball" },
	{ href: "./swf/iwannawin/base.html", imgSrc: "iwannawin.jpg", name: "I Wanna Win" },
	{ href: "./swf/jellygo/base.html", imgSrc: "jellygo.jpg", name: "Jelly Go!" },
	{ href: "./swf/littlewheel/base.html", imgSrc: "littlewheel.jpg", name: "Little Wheel" },
	{ href: "./swf/miniputt3/base.html", imgSrc: "miniputt3.jpg", name: "Mini Putt 3" },
	{ href: "./swf/minitrain/base.html", imgSrc: "minitrain.jpg", name: "Mini Train" },
	{ href: "./swf/papabakeria/base.html", imgSrc: "papasbakeria.jpg", name: "Papas Bakeria" },
	{ href: "./swf/papaburgeria/base.html", imgSrc: "papasburgeria.jpg", name: "Papas Burgeria" },
	{ href: "./swf/papacheeseria/base.html", imgSrc: "papascheeseria.jpg", name: "Papas Cheeseria" },
	{ href: "./swf/papacupcakeria/base.html", imgSrc: "papascupcakeria.jpg", name: "Papas Cupcakeria" },
	{ href: "./swf/papadonuteria/base.html", imgSrc: "papadonuteria.jpg", name: "Papas Donuteria" },
	{ href: "./swf/papafreezeria/base.html", imgSrc: "papasfreezeria.jpg", name: "Papas Freezeria" },
	{ href: "./swf/papahotdoggeria/base.html", imgSrc: "papashotdoggeria.jpg", name: "Papas Hotdoggeria" },
	{ href: "./swf/papapancakeria/base.html", imgSrc: "papaspancakeria.jpg", name: "Papas Pancakeria" },
	{ href: "./swf/papapasteria/base.html", imgSrc: "papaspasteria.jpg", name: "Papas Pasteria" },
	{ href: "./swf/papapizzeria/base.html", imgSrc: "papaspizzeria.jpg", name: "Papas Pizzeria" },
	{ href: "./swf/papascooperia/base.html", imgSrc: "papasscooperia.jpg", name: "Papas Scooperia" },
	{ href: "./swf/papasushiria/base.html", imgSrc: "papassushiria.jpg", name: "Papas Sushiria" },
	{ href: "./swf/papataco/base.html", imgSrc: "papataco.jpg", name: "Papas Taco Mia" },
	{ href: "./swf/papawingeria/base.html", imgSrc: "papawingeria.jpg", name: "Papas Wingeria" },
	{ href: "./swf/portal/base.html", imgSrc: "portal.jpg", name: "Portal" },
	{ href: "./swf/pvz2/base.html", imgSrc: "pvz2.jpg", name: "Plants Vs. Zombies 2" },
	{ href: "./swf/raftwars/base.html", imgSrc: "raftwars.jpg", name: "Raft Wars" },
	{ href: "./swf/scrapmeatalheros/base.html", imgSrc: "scrapmeatalheros.jpg", name: "Scrap Meatal Heros" },
	{ href: "./swf/shapeshifter/base.html", imgSrc: "shapeshifter.png", name: "Shape Shifter" },
	{ href: "./swf/squarehero/base.html", imgSrc: "squarehero.jpg", name: "Square Hero" },
	{ href: "./swf/tarzanball/base.html", imgSrc: "tarzanball.jpg", name: "Tarzan Ball" },
	{ href: "./swf/tastyplanetdinotime/base.html", imgSrc: "tastyplanetdinotime.jpg", name: "Tasty Planet Dinotime" },
	{ href: "./swf/truckloader/base.html", imgSrc: "truckloader.jpg", name: "Truck Loader" },
	{ href: "./swf/workingstiffs/base.html", imgSrc: "workingstiffs.jpg", name: "Working Stiffs" },
	{ href: "./html/eaglecraft/game/Offline_Download_Version.html", imgSrc: "minecraft.jpeg", name: "Minecraft (1.5.2 Eaglercraft)" },
	{ href: "./html/sm64/index.html", imgSrc: "sm64.jpg", name: "Super Mario 64" },
	{ href: "./html/rocket league/index.html", imgSrc: "rocketleague.jpg", name: "Rocket League" },
	{ href: "./html/google-snake/index.html", imgSrc: "googlesnake.jpg", name: "Google Snake" },
	{ href: "./html/stickman-hook/index.html", imgSrc: "stickmanhook.jpg", name: "Stickman Hook" },
	{ href: "./html/slope2/index.html", imgSrc: "slope2.jpg", name: "Slope 2" },
	{ href: "./html/slope/index.html", imgSrc: "slope.webp", name: "Slope" },
	{ href: "./html/bitlife/index.html", imgSrc: "bitlife.jpg", name: "Bitlife" },
	{ href: "./html/drift-boss/index.html", imgSrc: "drift-boss.png", name: "Drift Boss" },
	{ href: "./html/snow-rider-3d/index.html", imgSrc: "snow-rider-3d-unblocked.png", name: "Snow Rider 3D" },
	{ href: "./html/planetlife/index.html", imgSrc: "planetlife.jpg", name: "Planet Life" },
	{ href: "./swf/findingsanta/base.html", imgSrc: "santa.png", name: "Finding Santa" },
	{ href: "./swf/hauntthehouse/base.html", imgSrc: "hauntthehouse.jpg", name: "Haunt the House" },
	{ href: "./html/houseofhazards/index.html", imgSrc: "houseofhazards.jpg", name: "House of Hazards" },
	{ href: "./html/couch2048/index.html", imgSrc: "couch.jpg", name: "Couch 2048" },
	{ href: "./html/tabs/index.html", imgSrc: "tabs.jpeg", name: "Tabs" },
	{ href: "./html/catpitolists/advcap.html", imgSrc: "capitolist.jpeg", name: "AdVenture Capitolists" },
	{ href: "./swf/ducklife1/base.html", imgSrc: "ducklife.webp", name: "Duck Life" },
	{ href: "./swf/ducklife2/base.html", imgSrc: "ducklife2.webp", name: "Duck Life 2" },
	{ href: "./swf/ducklife3/base.html", imgSrc: "ducklife3.webp", name: "Duck Life 3" },
	{ href: "./swf/factoryballs1/base.html", imgSrc: "factoryballs1.jpeg", name: "Factory Balls 1" },
	{ href: "./swf/factoryballs2/base.html", imgSrc: "factoryballs2.jpeg", name: "Factory Balls 2" },
	{ href: "./swf/factoryballs3/base.html", imgSrc: "factoryballs3.jpeg", name: "Factory Balls 3" },
	{ href: "./swf/factoryballs4/base.html", imgSrc: "factoryballs4.jpeg", name: "Factory Balls 4" },
	{ href: "./swf/run/base.html", imgSrc: "run.jpeg", name: "Run 1" },
	{ href: "./swf/run2/base.html", imgSrc: "run2.jpeg", name: "Run 2" },
	{ href: "./html/bitts/index.html", imgSrc: "bitts.png", name: "Big Ice Tower Tiny Square" },
	{ href: "./swf/fancy1/base.html", imgSrc: "fancy1.jpg", name: "Fancy Pants 1" },
	{ href: "./swf/fancy3/base.html", imgSrc: "fancy3.jpg", name: "Fancy Pants 3" },
	{ href: "./swf/penguin/base.html", imgSrc: "penguin.jpeg", name: "Penguin Dinner" },
	{ href: "./swf/bombit/base.html", imgSrc: "bombit.jpeg", name: "Bombit 1" },
	{ href: "./swf/bombit2/base.html", imgSrc: "bombit2.jpeg", name: "Bombit 2" },
	{ href: "./swf/bombit3/base.html", imgSrc: "bombit3.jpg", name: "Bombit 3" },
	{ href: "./swf/comicbook/base.html", imgSrc: "comicbook.jpeg", name: "Comic Book Cody" },
	{ href: "./swf/hotdogbush/base.html", imgSrc: "hotdogbush.jpeg", name: "Hot Dog Bush" },
	{ href: "./swf/louie1/base.html", imgSrc: "louie1.jpeg", name: "Papa Louies 1" },
	{ href: "./swf/minhero/base.html", imgSrc: "minhero.jpeg", name: "Min Hero Tower of Sages" },
	{ href: "./swf/pandas1/base.html", imgSrc: "pandas1.jpeg", name: "3 Pandas 1" },
	{ href: "./swf/shapeswitch/base.html", imgSrc: "shapeswitcher.jpeg", name: "Shape Switcher" },
	{ href: "./swf/strikeforcekitty/base.html", imgSrc: "strikeforcekitty.jpeg", name: "Strike Force Kitty 1" },
	{ href: "./swf/strikeforcekitty2/base.html", imgSrc: "strikeforcekitty2.jpeg", name: "Strike Force Kitty 2" },
	{ href: "./swf/strikeforcekitty3/base.html", imgSrc: "strikeforcekitty3.jpeg", name: "Strike Force Kitty 3" },
	{ href: "./swf/sugar/base.html", imgSrc: "sugar.jpeg", name: "Sugar, Sugar" },
	{ href: "./html/drive-mad/index.html", imgSrc: "drivemad.jpg", name: "Drive Mad" },
	{ href: "./html/among-us/index.html", imgSrc: "amongus.png", name: "Among Us" },
	{ href: "./html/bob-the-robber-2/index.html", imgSrc: "bob.jpeg", name: "Bob the Robber 2" },
	{ href: "./html/tiny-fishing/index.html", imgSrc: "fishing.jpeg", name: "Tiny Fishing" },
	{ href: "./html/2048-master/2048-master/index.html", imgSrc: "2048.png", name: "2048" },
	{ href: "./html/adarkroom/index.html", imgSrc: "adarkroom.png", name: "A Dark Room" },
	{ href: "./html/algaes-escapade/index.html", imgSrc: "apple-touch-icon-114x114.png", name: "Algaes Escapade" },
	{ href: "./html/Alien Invasion/Alien Invasion/index.html", imgSrc: "alien.png", name: "Alien Invasion" },
	{ href: "./html/Appel/game/Appel.html", imgSrc: "appel.png", name: "Appel" },
	{ href: "./html/asciispace/index.html", imgSrc: "asciispace.png", name: "Asciispace" },
	{ href: "./html/asteroids/index.html", imgSrc: "asteroids.png", name: "Asteroids" },
	{ href: "./html/astray/index.html", imgSrc: "astray.png", name: "Astray" },
	{ href: "./html/ball platformer/game/ball platformer.html", imgSrc: "ball platformer.png", name: "Ball Platformer" },
	{ href: "./html/blackholesquare/index.html", imgSrc: "BlackHoleSquare.png", name: "Blackholesquare" },
	{ href: "./html/bloxorz/game/index.html", imgSrc: "bloxorz.png", name: "Bloxorz" },
	{ href: "./html/bounceback/index.html", imgSrc: "bounceback.png", name: "Bounceback" },
	{ href: "./html/breaklock/index.html", imgSrc: "breaklock.png", name: "Breaklock" },
	{ href: "./html/breakout/index.html", imgSrc: "breakout.png", name: "Breakout" },
	{ href: "./html/Bubble Scratch/game/Bubble Scratch.html", imgSrc: "bubble scratch.png", name: "Bubble Scratch" },
	{ href: "./html/c4/game/index.html", imgSrc: "c4.png", name: "Connect 4" },
	{ href: "./html/captaincallisto/index.html", imgSrc: "capain.png", name: "Captain Callisto" },
	{ href: "./html/chess/index.html", imgSrc: "chess.png", name: "Chess" },
	{ href: "./html/chroma/index.html", imgSrc: "chroma.png", name: "Chroma" },
	{ href: "./html/cookieclicker/index.html", imgSrc: "cookie.png", name: "Cookie Clicker" },
	{ href: "./html/Crystal Seeker.html", imgSrc: "crystal.png", name: "Crystal Seeker" },
	{ href: "./html/Cube Miner/game/Cube Miner.html", imgSrc: "cube.png", name: "Cube Miner" },
	{ href: "./html/cubefield/index.html", imgSrc: "cubefeild.png", name: "Cubefield" },
	{ href: "./html/digger-main/digger-main/index.html", imgSrc: "diggermain.png", name: "Digger Main" },
	{ href: "./html/dinosaur/index.html", imgSrc: "dino.png", name: "Dinosaur" },
	{ href: "./html/edgenotfound/index.html", imgSrc: "edge.png", name: "Edge Not Found" },
	{ href: "./html/evilglitch/index.html", imgSrc: "EvilGlitch.png", name: "Evil Glich" },
	{ href: "./html/flappy-2048/index.html", imgSrc: "flappy2048.png", name: "Flappy 2048" },
	{ href: "./html/flappybird/index.html", imgSrc: "FlappyBird.png", name: "Flappy Bird" },
	{ href: "./html/Fortnite Z/game/Fortnite Z.html", imgSrc: "fornitez.png", name: "Fortnite Z" },
	{ href: "./html/fruitninja/index.html", imgSrc: "fruit.png", name: "Fruit Ninja" },
	{ href: "./html/Geometry Dash Meltdown/game/Geometry Dash Meltdown.html", imgSrc: "dashmeltdown.png", name: "Geometry Dash Meltdown" },
	{ href: "./html/Geometry Dash Subzero/game/Geometry Dash Subzero.html", imgSrc: "dashsubzero.png", name: "Geometry Dash Subzero" },
	{ href: "./html/Geometry Dash v1/game/Geometry Dash v1.html", imgSrc: "dash.png", name: "Geometry Dash" },
	{ href: "./html/Geometry Dash World Toxic factory/game/Geometry Dash World Toxic factory.html", imgSrc: "dashtoxic.png", name: "Geometry Dash World Toxic" },
	{ href: "./html/Getting Over It v1/game/Getting Over It v1.html", imgSrc: "over.png", name: "Getting Over It" },
	{ href: "./html/hearse mster/-=HORSE MASTER=- The Game of Horse Mastery.html", imgSrc: "horse.png", name: "Horse Master" },
	{ href: "./html/hextris/index.html", imgSrc: "hex.png", name: "Hextris" },
	{ href: "./html/html5-farming-demo-master/html5-farming-demo-master/farming.html", imgSrc: "farm.png", name: "Farming" },
	{ href: "./html/konnekt/index.html", imgSrc: "cone.png", name: "Konnekt" },
	{ href: "./html/Mario/game/Mario.html", imgSrc: "Mario.png", name: "Mario" },
	{ href: "./html/minekhan/index.html", imgSrc: "khan.png", name: "MineKahn" },
	{ href: "./html/Paper Minecraft/game/Paper Minecraft.html", imgSrc: "papermc.png", name: "Paper Minecraft" },
	{ href: "./html/packabunchas/index.html", imgSrc: "pack.png", name: "Packabunchas" },
	{ href: "./html/just one boss/index.html", imgSrc: "oneboss.png", name: "Just One Boss" },
	{ href: "./html/pushback/index.html", imgSrc: "back.png", name: "Push Back" },
	{ href: "./html/racer/index.html", imgSrc: "racer.jpeg", name: "Racer" },
	{ href: "./html/radius raid/radius raid/index.html", imgSrc: "radius.png", name: "Radius Raid" },
	{ href: "./html/pico-8/PICO-8 Cartridge.html", imgSrc: "pcraft.png", name: "P-Craft" },
	{ href: "./html/retrohaunt/index.html", imgSrc: "retro.jpeg", name: "Retrohaunt" },
	{ href: "./html/roadblocks/index.html", imgSrc: "roadblocks.jpeg", name: "Roadblocks" },
	{ href: "./html/shuttledeck/index.html", imgSrc: "shuttle.png", name: "Shuttledeck" },
	{ href: "./html/sleeping beauty/sleeping beauty/index.html", imgSrc: "sleeping.png", name: "Sleeping Beauty" },
	{ href: "./html/spacecompany/index.html", imgSrc: "images.png", name: "Space Company" },
	{ href: "./html/spacegarden/index.html", imgSrc: "garden.jpeg", name: "Space Garden" },
	{ href: "./html/spacehuggers/index.html", imgSrc: "huggers.jpeg", name: "Space Huggers" },
	{ href: "./html/stack/stack/index.html", imgSrc: "stack.jpeg", name: "Stack" },
	{ href: "./html/tetris advanced/index.html", imgSrc: "tetris.jpeg", name: "Tetris" },
	{ href: "./html/trimps/index.html", imgSrc: "trimps.png", name: "Trimps" },
	{ href: "./html/xx142-b2exe/index.html", imgSrc: "xx.png", name: "xx142-b2exe" },
	{ href: "./html/Sand and Water v3.html", imgSrc: "sand.png", name: "Sand and Water" },
	{ href: "./html/Scratch Brawl 2.html", imgSrc: "scratchb.jpg", name: "Scratch Brawl 2" },
	{ href: "./html/slither.io v1.html", imgSrc: "slither.png", name: "Slither.io" },
	{ href: "./html/Terrain Generator.html", imgSrc: "terrain.png", name: "Terrain Generator" },
	{ href: "./html/Terraria.html", imgSrc: "terraria.jpg", name: "Terraria" },
	{ href: "./html/The Ninja.html", imgSrc: "n1.webp", name: "The Ninja" },
	{ href: "./html/The Ninja 2.html", imgSrc: "n2.png", name: "The Ninja 2" },
	{ href: "./html/The Ninja 3.html", imgSrc: "n3.webp", name: "The Ninja 3" },
	{ href: "./html/The Ninja 4.html", imgSrc: "n4.jpg", name: "The Ninja 4" },
	{ href: "./html/The Ninja 5.html", imgSrc: "n5.webp", name: "The Ninja 5" },
	{ href: "./html/The Ninja 5 Hacked!.html", imgSrc: "n5h.png", name: "The Ninja 5 Hacked" },
	{ href: "./html/100uc.html", imgSrc: "100uc.png", name: "$100 Unicorn" },
	{ href: "./html/theexocutor", imgSrc: "executor.png", name: "The Executor" },
	{ href: "./html/1v1/index.html", imgSrc: "1v1.webp", name: "1v1.lol" },
	{ href: "./html/1v1space/index.html", imgSrc: "1v1space.webp", name: "1v1 Space" },
	{ href: "./html/10-minutes-till-dawn/index.html", imgSrc: "10m.webp", name: "10 Minutes Till Dawn" },
	{ href: "./html/100-player-pong/index.html", imgSrc: "100pong.webp", name: "100 Pong" },
	{ href: "./html/9007199254740992/index.html", imgSrc: "900.webp", name: "9007199254740992" },
	{ href: "./html/achievementunlocked/index.html", imgSrc: "ache.webp", name: "Achievementunlocked" },
	{ href: "./html/ages-of-conflict/index.html", imgSrc: "ages-of-conflict.webp", name: "Ages of Conflict" },
	{ href: "./html/alienhominid/index.html", imgSrc: "alienhominid.webp", name: "Alien Hominid" },
	{ href: "./html/amidst-the-clouds/index.html", imgSrc: "amidst-the-clouds.webp", name: "Amidst the Clouds" },
	{ href: "./html/avalanche/index.html", imgSrc: "avalanche.webp", name: "Avalanche" },
	{ href: "./html/backrooms/index.html", imgSrc: "backrooms.webp", name: "Backrooms" },
	{ href: "./html/bad-ice-cream/index.html", imgSrc: "bad-ice-cream.webp", name: "Bad Icecream" },
	{ href: "./html/bad-ice-cream-2/index.html", imgSrc: "bad-ice-cream-2.webp", name: "Bad Icecream 2" },
	{ href: "./html/bad-ice-cream-3/index.html", imgSrc: "bad-ice-cream-3.webp", name: "Bad Icecream 3" },
	{ href: "./html/baldis-basics/index.html", imgSrc: "baldis-basics.webp", name: "Baldis Basics" },
	{ href: "./html/ball-hop/index.html", imgSrc: "ballhop.webp", name: "Ballhop" },
	{ href: "./html/ballistic-chickens/index.html", imgSrc: "ballistic-chickens.webp", name: "Ballistic Chickens" },
	{ href: "./html/basketball-stars/index.html", imgSrc: "BAS.webp", name: "Basketball Stars" },
	{ href: "./html/biters-io/index.html", imgSrc: "biters.webp", name: "Biters" },
	{ href: "./html/blocky-tower/index.html", imgSrc: "blocky.webp", name: "Blocky tower" },
	{ href: "./html/bloonstd/index.html", imgSrc: "bloonstd.webp", name: "Bloonstd" },
	{ href: "./html/bloonstd2/index.html", imgSrc: "bloonstd2.webp", name: "Bloonstd 2" },
	{ href: "./html/bloonstd4/index.html", imgSrc: "bloonstd4.webp", name: "Bloonstd 4" },
	{ href: "./html/boxing-physics/index.html", imgSrc: "box.webp", name: "Boxing" },
	{ href: "./html/breakout/index.html", imgSrc: "breakout.webp", name: "Breakout" },
	{ href: "./html/browserquest/index.html", imgSrc: "BrowserQuest.webp", name: "Browserquest" },
	{ href: "./html/big-tower-tiny-square/index.html", imgSrc: "btts.webp", name: "Big Tower Tiny Square" },
	{ href: "./html/circlo/index.html", imgSrc: "circlo.webp", name: "Circlo" },
	{ href: "./html/cluster-rush/index.html", imgSrc: "cluster.webp", name: "Cluster Rush" },
	{ href: "./html/connect3/index.html", imgSrc: "con3.webp", name: "Connect 3" },
	{ href: "./html/core-ball/index.html", imgSrc: "coreball.webp", name: "Coreball" },
	{ href: "./html/crossyroad/index.html", imgSrc: "crossyroad.webp", name: "Crossyroad" },
	{ href: "./html/csgo-clicker/index.html", imgSrc: "CSGO.webp", name: "CSGO Clicker" },
	{ href: "./html/cuttherope/index.html", imgSrc: "ctr.webp", name: "Cut the Rope" },
	{ href: "./html/cupcakes/index.html", imgSrc: "cupcakes.webp", name: "Cupcake 2048" },
	{ href: "./html/cyber-city-driver/index.html", imgSrc: "cyber.webp", name: "Cyber City Driver" },
	{ href: "./html/dogeminer/index.html", imgSrc: "Dogecoin.webp", name: "Dogeminer" },
	{ href: "./html/doodlejump/index.html", imgSrc: "doodle.webp", name: "Doodle Jump" },
	{ href: "./html/drift-city/index.html", imgSrc: "driftc.webp", name: "Drift City" },
	{ href: "./html/driftking/index.html", imgSrc: "driftking.webp", name: "Drift King" },
	{ href: "./html/dunkers-fight/index.html", imgSrc: "dunk.webp", name: "Dunkers Fight" },
	{ href: "./html/eatio/index.html", imgSrc: "eatio.webp", name: "Eatio" },
	{ href: "./html/edge-surf/index.html", imgSrc: "edge-surf.webp", name: "Ede Surf" },
	{ href: "./html/eel-slap/index.html", imgSrc: "eel-slap.webp", name: "Eel Slap" },
	{ href: "./html/eggy-car/index.html", imgSrc: "eggy-car.webp", name: "Eggy Car" },
	{ href: "./html/steal-this-election/index.html", imgSrc: "elec.webp", name: "Steal this Election" },
	{ href: "./html/endlesswar3/index.html", imgSrc: "endlesswar3.webp", name: "Endless War 3" },
	{ href: "./html/evolution/index.html", imgSrc: "evolution.webp", name: "Evolution" },
	{ href: "./html/exo/index.html", imgSrc: "exo.webp", name: "Exo" },
	{ href: "./html/flappyplane/index.html", imgSrc: "flappyplae.jpeg", name: "Flappy Plane" },
	{ href: "./html/fliphero/index.html", imgSrc: "fliphero.webp", name: "Flip Hero" },
	{ href: "./html/fnaf/index.html", imgSrc: "fnaf.webp", name: "FNAF" },
	{ href: "./html/fnaf2/index.html", imgSrc: "fnaf.webp", name: "FNAF 2" },
	{ href: "./html/fnaf3/index.html", imgSrc: "fnaf.webp", name: "FNAF 3" },
	{ href: "./html/fnaf4/index.html", imgSrc: "fnaf.webp", name: "FNAF 4" },
	{ href: "./html/fruitninja/index.html", imgSrc: "fruitninja.webp", name: "Fruit Ninja" },
	{ href: "./html/funnyshooter/index.html", imgSrc: "funnyshooter.webp", name: "Funny Shooter" },
	{ href: "./html/goodnight/index.html", imgSrc: "gn.webp", name: "Goodnight" },
	{ href: "./html/idle-breakout/index.html", imgSrc: "idlebreakout.webp", name: "Idle Breakout" },
	{ href: "./html/impossiblequiz/index.html", imgSrc: "impossiblequiz.webp", name: "Impossible Quiz" },
	{ href: "./html/interactivebuddy/index.html", imgSrc: "interactivebuddy.webp", name: "Interactive Buddy" },
	{ href: "./html/jetpack-joyride/index.html", imgSrc: "jetpack-joyride.webp", name: "Jetpack Joyride" },
	{ href: "./html/just-fall/index.html", imgSrc: "just-fall.webp", name: "Just Fall" },
	{ href: "./html/kitchen-gun-game/index.html", imgSrc: "kitchen-gun-game.webp", name: "Kitchen Gun Game" },
	{ href: "./html/kittencannon/index.html", imgSrc: "kittencannon.webp", name: "Kitten Cannon" },
	{ href: "./html/krunker/index.html", imgSrc: "krunker.webp", name: "Krunker" },
	{ href: "./html/learntofly/index.html", imgSrc: "learntofly.webp", name: "Learn to Fly" },
	{ href: "./html/motox3m-spooky/index.html", imgSrc: "moto-spook.webp", name: "Moto X3M Spooky" },
	{ href: "./html/motox3m-pool/index.html", imgSrc: "motox3m-pool.webp", name: "Moto X3M Pool" },
	{ href: "./html/motox3m-winter/index.html", imgSrc: "motox3m-winter.webp", name: "Moto X3M Winter" },
	{ href: "./html/motox3m/index.html", imgSrc: "motox3m.webp", name: "Moto X3M" },
	{ href: "./html/motox3m2/index.html", imgSrc: "motox3m2.webp", name: "Moto X3M 2" },
	{ href: "./html/2048-multitask/index.html", imgSrc: "multit.webp", name: "2048 Multitask" },
	{ href: "./html/pacman/index.html", imgSrc: "pacman.webp", name: "Pacman" },
	{ href: "./html/paperio/index.html", imgSrc: "paperio.webp", name: "Paper.io" },
	{ href: "./html/papery-planes/index.html", imgSrc: "paperplane.webp", name: "Papery Planes" },
	{ href: "./html/particle-clicker/index.html", imgSrc: "parclick.webp", name: "Particle Clicker" },
	{ href: "./html/picky-package/index.html", imgSrc: "pickyback.webp", name: "Picky Package" },
	{ href: "./html/pokemonfirered/index.html", imgSrc: "PokemonFireRed.webp", name: "Pokemon Fire Red" },
	{ href: "./html/pong/index.html", imgSrc: "pong.webp", name: "Pong" },
	{ href: "./html/racer/index.html", imgSrc: "Racer.webp", name: "Racer" },
	{ href: "./html/retrobowl/index.html", imgSrc: "retrobowl.webp", name: "Retro Bowl" },
	{ href: "./html/rooftop-snipers-2/index.html", imgSrc: "Rooftop-Snipers.webp", name: "Rooftop Snipers" },
	{ href: "./html/sans/index.html", imgSrc: "sans.webp", name: "Sans" },
	{ href: "./html/idle-shark/index.html", imgSrc: "sharkgame.webp", name: "Idle Shark" },
	{ href: "./html/spaceinvaders/index.html", imgSrc: "spaceinv.webp", name: "Space Invaders" },
	{ href: "./html/stack/index.html", imgSrc: "stack.webp", name: "Stack" },
	{ href: "./html/stack-ball/index.html", imgSrc: "stackball.webp", name: "Stack Ball" },
	{ href: "./html/subwaysurferssanfrancisco/index.html", imgSrc: "subsan.webp", name: "Subway Surfers San Fran" },
	{ href: "./html/subwaysurfersbeijing/index.html", imgSrc: "subwaysurferbeijing.webp", name: "Subway Surfers BeiJing" },
	{ href: "./html/subwaysurfershouston/index.html", imgSrc: "subwaysurfershouston.webp", name: "Subway Surfers Houston" },
	{ href: "./html/subwaysurfersmonaco/index.html", imgSrc: "SubwayMonaco.webp", name: "Subway Surfers Monaco" },
	{ href: "./html/temple-run-2/index.html", imgSrc: "templerun.webp", name: "Temple Run 2" },
	{ href: "./html/thesquare/index.html", imgSrc: "thesquare.webp", name: "The Square" },
	{ href: "./html/timeshooter/index.html", imgSrc: "timeshooters.webp", name: "Time Shooters" },
	{ href: "./html/tic-tac-toe/index.html", imgSrc: "toe.webp", name: "Tic-Tac-Toe" },
	{ href: "./html/tic-tac-toe-ai/index.html", imgSrc: "toeai.webp", name: "Tic-Tac-Toe AI" },
	{ href: "./html/towermaster/index.html", imgSrc: "towermaster.webp", name: "Tower Master" },
	{ href: "./html/tunnelrush/index.html", imgSrc: "tunnelrush.webp", name: "Tunnel Rush" },
	{ href: "./html/tv-static/index.html", imgSrc: "tv-static.webp", name: "TV Static" },
	{ href: "./html/veloce/index.html", imgSrc: "VELOCE.webp", name: "Veloce" },
	{ href: "./html/vex3/index.html", imgSrc: "vex3.webp", name: "Vex 3" },
	{ href: "./html/vex4/index.html", imgSrc: "vex4.webp", name: "Vex 4" },
	{ href: "./html/vex5/index.html", imgSrc: "vex5.webp", name: "Vex 5" },
	{ href: "./html/vex6/index.html", imgSrc: "vex6.webp", name: "Vex 6" },
	{ href: "./html/vex7/index.html", imgSrc: "vex7.webp", name: "Vex 7" },
	{ href: "./html/wallsmash/index.html", imgSrc: "wallsmash.webp", name: "Wall Smash" },
	{ href: "./html/waterworks/index.html", imgSrc: "waterworks.webp", name: "Water Works" },
	{ href: "./html/weavesilk/index.html", imgSrc: "weavesilk.webp", name: "Weave Silk" },
	{ href: "./html/webgl-fluid-simulation/index.html", imgSrc: "webgl-fluid-simulation.webp", name: "Fluid Simulation" },
	{ href: "./html/webretro/index.html", imgSrc: "webretro.webp", name: "Web Retro" },
	{ href: "./html/whac-a-mole/index.html", imgSrc: "Whac-A-Mole.webp", name: "Whac-A-Mole" },
	{ href: "./html/worlds-hardest-game/index.html", imgSrc: "whg.webp", name: "World's Hardest Game" },
	{ href: "./html/wordle/index.html", imgSrc: "wordle.webp", name: "Wordle" },
	{ href: "./html/x-trial-racing/index.html", imgSrc: "xtr.webp", name: "X Trial Racing" },
	{ href: "./html/yoshifabrication/index.html", imgSrc: "YFS.webp", name: "Yoshi Fabricator" },
	{ href: "./html/zombs-royale/index.html", imgSrc: "zombs-royale.webp", name: "Zombs Royale" },
	{ href: "./html/zoro/index.html", imgSrc: "zoro.webp", name: "Zoro" },
	{ href: "./html/lozmaker/game/lozmaker.html", imgSrc: "lozmaker.png", name: "Ledegnd of Zelda Maker" },
	{ href: "./html/towerdef.html", imgSrc: "towerdef.png", name: "Tower Defence" },
	{ href: "./html/yetanotherworld.html", imgSrc: "yetanotherworld.png", name: "Yet Another World" },
	{ href: "./html/afterlife/game/afterlife.html", imgSrc: "afterlife.png", name: "Afterlife" },
	{ href: "./html/earthsausage/game/earthsausage.html", imgSrc: "earth.png", name: "Earth Sausage" },
	{ href: "./html/flatguys/game/flatguys.html", imgSrc: "flatguys.png", name: "Flat Guys" },
	{ href: "./html/monke/game/monke.html", imgSrc: "monke.png", name: "Monke" },
	{ href: "./html/pixelbearadventure/game/pixelbearadventure.html", imgSrc: "pixelbearadventure.png", name: "Pixel Bear Adventure" },
	{ href: "./html/pixelspeedrun/game/pixelspeedrun.html", imgSrc: "pixelspeedrun.png", name: "Pixel Speedrun" },
	{ href: "./html/pizzachallenge/game/pizzachallenge.html", imgSrc: "pizzachallenge.png", name: "Pizza Challange" },
	{ href: "./html/retro speed/game/retro speed.html speed.html", imgSrc: "retro speed.png", name: "Retro Speed" },
	{ href: "./html/tank trouble 2.html", imgSrc: "tank trouble 2.png", name: "Tank Trouble 2" },
];

