export const siteMapping = {
  "mathcord.netlify.app": ["https://mathcord2.netlify.app", "https://mathcord3.netlify.app"],
  "mathcord2.netlify.app": ["https://mathcord.netlify.app", "https://mathcord3.netlify.app"],
  "mathcord3.netlify.app": ["https://mathcord.netlify.app", "https://mathcord2.netlify.app"],
  "strongdog.netlify.app": ["https://strongdog2.netlify.app", "https://strongdog3.netlify.app"],
  "strongdog2.netlify.app": ["https://strongdog.netlify.app", "https://strongdog3.netlify.app"],
  "strongdog3.netlify.app": ["https://strongdog.netlify.app", "https://strongdog2.netlify.app"],
  "stroongdog.netlify.app": ["https://stroongdog2.netlify.app", "https://stroongdog3.netlify.app"],
  "stroongdog2.netlify.app": ["https://stroongdog.netlify.app", "https://stroongdog3.netlify.app"],
  "stroongdog3.netlify.app": ["https://stroongdog.netlify.app", "https://stroongdog2.netlify.app"],
  "jman1593.github.io": ["https://jman1593.github.io/strongdog2", "https://jman1593.github.io/strongdog3"],
  "jman1593.github.io/strongdog2": ["https://jman1593.github.io", "https://jman1593.github.io/strongdog3"],
  "jman1593.github.io/strongdog3": ["https://jman1593.github.io", "https://jman1593.github.io/strongdog2"],
  "strongdog-1.vercel.app": ["https://strongdog2.vercel.app", "https://strongdog3.vercel.app"],
  "strongdog2.vercel.app": ["https://strongdog-1.vercel.app", "https://strongdog3.vercel.app"],
  "strongdog3.vercel.app": ["https://strongdog-1.vercel.app", "https://strongdog2.vercel.app"],
  "127.0.0.1": ["http://127.0.0.1:8080/strongdog2", "http://127.0.0.1:8080/strongdog3"],
  "127.0.0.1:8080/strongdog2": ["127.0.0.1", "http://127.0.0.1:8080/strongdog3"],
  "127.0.0.1:8080/strongdog3": ["127.0.0.1", "http://127.0.0.1:8080/strongdog2"],
  "strongdog.com": ["https://strongdog.com/strongdog2", "https://strongdog.com/strongdog3"],
  "strongdog.com/strongdog2": ["strongdog.com", "https://strongdog.com/strongdog3"],
  "strongdog.com/strongdog3": ["strongdog.com", "https://strongdog.com/strongdog2"],
  "mathcord.com": ["https://mathcord.com/strongdog2", "https://mathcord.com/strongdog3"],
  "mathcord.com/strongdog2": ["mathcord.com", "https://mathcord.com/strongdog3"],
  "mathcord.com/strongdog3": ["mathcord.com", "https://mathcord.com/strongdog2"],
};
